owncloud/docs-ocis

README.md, docs/new-version-branch.md, docs/the-branching-workflow.md
=> some fixes

modules/ROOT/pages/configuration/index.adoc, modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/installation/index.adoc, modules/ROOT/pages/maintenance/index.adoc, modules/ROOT/pages/migration/index.adoc, modules/ROOT/pages/prerequisites/index.adoc, modules/ROOT/partials/nav.adoc
First baby steps to a new guide.
=> Content structure (draft)

modules/ROOT/pages/index.adoc
=> A few more topics added

modules/ROOT/pages/index.adoc
This will likely become larger section.
=> own heading for architecture

modules/ROOT/pages/architecture/index.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/partials/nav.adoc
Add a architecture and concepts section
=> add architecture and concepts

modules/ROOT/pages/deployment/index.adoc
Collected deployment topics and content for securing oCIS.
=> Deployment structure

modules/ROOT/pages/deployment/index.adoc
Comments and fixes, plus demo user passwords added.
=> content additions and revisions

site.yml
=> typo fix in comment

modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/installation/index.adoc, modules/ROOT/partials/nav.adoc
=> removed installation section

modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/prerequisites/index.adoc, site.yml
=> Basic setup and prerequisites added

site.yml
add the common latest_xxx_version to site.yml for ease of building when referenced
=> add latest_xxx_version to site.yml

modules/ROOT/pages/index.adoc
=> introduction added

modules/ROOT/pages/configuration/index.adoc, modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/index.adoc
systemd configuration, more structure and info in general
=> systemd config and more

modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/prerequisites/index.adoc
found a better place to include NFS, but this is still not final.
=> moved nfs inclusion to deployment

modules/ROOT/pages/deployment/index.adoc
apparently page$ is necessary with include but not with xref
=> inserted page$ again in the include.

modules/ROOT/pages/architecture/index.adoc, modules/ROOT/pages/prerequisites/index.adoc
=> some info on spaces and storage

modules/ROOT/pages/deployment/index.adoc
=> minor fixes

modules/ROOT/pages/architecture/index.adoc, modules/ROOT/pages/configuration/index.adoc, modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/maintenance/index.adoc, modules/ROOT/pages/migration/index.adoc, modules/ROOT/pages/prerequisites/index.adoc
preliminary tocs for each section, flatter or deeper might be necessary later.
=> added toc and levels

modules/ROOT/pages/index.adoc
Introduction:
Add info about bundled binary shipment - good to know that all is packed and delivered in a single binary
NOTE: introduced a comment named `fixme` we can easily search for when the puzzle pieces come together and we need to finalize things
=> Add info about bundled binary shipment

modules/ROOT/pages/index.adoc
Some additional improvements made
* Adding an introduction section
* Adding an prerequisites section
(the change is uploaded to staging to check how it looks like)
=> Additional improvements to the introduction page

modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/index.adoc
Have a more streamlined text for the introduction and deployment main page.
This is maybe not final, but mergable to have a good starting point
=> Update Introduction and Deployment main page

modules/ROOT/pages/prerequisites/index.adoc
Main changes in the hardware section, added a virtualisation section
Changes uploaded to staging
Note that there is no WAN (internet access) bandwidth consideration mentioned (currently LAN only, but not mentioned explicitly). This consideration is to be discussed, but my gut feeling tells that we should mention it.
=> Improve the prerequisites documentation

modules/ROOT/pages/prerequisites/index.adoc
Update Hardware in Prerequisites.
Integrated info based on a call with H.v.Reth
(Separating the different topics for easing review.)
=> Update the Hardware section

modules/ROOT/pages/prerequisites/index.adoc
Update Bandwith Requirements in Prerequisites.
Integrated info based on a call with H.v.Reth
(Separating the different topics for easing review.)
=> Update Bandwith Requirements

modules/ROOT/pages/prerequisites/index.adoc
Improved the memory considerations
Improved the bandwidh considerations
Improved some text
Available on staging
=> Fix memory and other explanation

modules/ROOT/pages/prerequisites/index.adoc
@EParzefall as suggested,
already on staging...
=> Fix table layout in prerequisites

modules/ROOT/pages/prerequisites/index.adoc
Some content improvements and internal ink fixes in prerequisites.
=> Content improvements

modules/ROOT/pages/prerequisites/index.adoc
Improve table rendering and fix some text.
=> Fix table and some text

modules/ROOT/pages/prerequisites/index.adoc
Fintuning table sizes to avoid not necessary line breakes
=> Fintuning table sizes

modules/ROOT/pages/index.adoc
Improvement of the introduction page.
=> Update introduction page

modules/ROOT/pages/availability_scaling/index.adoc
Update based on feedback from @butonic 
Already visible on staging.
=> Fix availability based on feedback

modules/ROOT/pages/index.adoc
=> language review

modules/ROOT/pages/prerequisites/index.adoc
=> fixed typo

modules/ROOT/pages/architecture/index.adoc
* Mostly a reordering of items
* Itemize text for improved readbility
* Making example html links unclickable
* Setting the corret toc level
* Some text addons
=> Small fixes to the architecture guide - concepts section

modules/ROOT/images/availability_scaling/scale_up.svg
=> Improve scale up image

modules/ROOT/pages/deployment/docker/docker-setup.adoc
added packages to be installed. Should go into the prerequisites as well.
=> little additions

modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/extensions/index.adoc
=> improved deployment overview

modules/ROOT/pages/deployment/general/general-info.adoc
=> General info update

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/manual/manual-setup.adoc
Small fixes to the general info
More fixes in the manual install
=> Update manual install

modules/ROOT/pages/configuration/roles-permissions.adoc
Added some content on the different roles and permissions for spaces.
=> roles and permissions

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/manual/manual-setup.adoc
A bunch of changes to fix systemd,
additional changes needed in general info.
=> Changes for systemd

modules/ROOT/pages/availability_scaling/index.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/manual/manual-setup.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/prerequisites/index.adoc
=> Some smaller fixes

modules/ROOT/pages/deployment/general/general-info.adoc
=> Text fix/improvement

modules/ROOT/pages/deployment/manual/manual-setup.adoc, site.yml
Some things have changed, fixed.
=> Fix manual setup based on changes from version 1.9.1 to 1.19.1

modules/ROOT/pages/deployment/general/general-info.adoc
Mostly fixes to the demo user stuff, some other things too...
=> Fixes to the demo user stuff

modules/ROOT/pages/deployment/general/general-info.adoc
=> Note text fix

modules/ROOT/pages/deployment/general/general-info.adoc
Correct the base bath info for manual install in general info
=> Correct base path

modules/ROOT/pages/deployment/manual/manual-setup.adoc
After rereading, some fixes to the manual installation
=> Some fixes to the manual installation

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/deployment/manual/manual-setup.adoc, site.yml
* Adding the admin user
* Fixing sections
* Fixing links
=> Adding the admin user

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/manual/manual-setup.adoc
Just some small fixes and improvements
=> Small fixes and improvements

modules/ROOT/pages/extensions/audit.adoc, modules/ROOT/partials/nav.adoc
harvested from dev guide. Some descriptions still missing.
=> Audit config variables

modules/ROOT/pages/extensions/webdav.adoc, modules/ROOT/partials/nav.adoc
environment variables (descriptions still missing) and example YAML file for the WebDAV extension
=> adding WebDAV extension

modules/ROOT/pages/extensions/audit.adoc, modules/ROOT/pages/extensions/webdav.adoc
very little content so far, but it's at least a reminder to improve the descriptions.
=> added descriptions

modules/ROOT/pages/deployment/docker/docker-setup.adoc
Fixes to the docker documentation, especially how to start the runtime
=> Docker fixes

modules/ROOT/pages/deployment/manual/manual-setup.adoc
Some improvements to the manual installation section
=> Improve manual installation

modules/ROOT/pages/deployment/docker/docker-setup.adoc
This is a first step towards the new docker content.
=> First improvements to docker

modules/ROOT/pages/deployment/docker/docker-setup.adoc
Next update to the docker page
Already in staging
=> Docker the next

modules/ROOT/pages/deployment/docker/docker-setup.adoc
=> Some Docker fixes

modules/ROOT/pages/deployment/docker/docker-setup.adoc
=> Small Docker Fix

modules/ROOT/pages/deployment/docker/docker-setup.adoc
More Docker stuff and tuning the sections
=> More Docker stuff

modules/ROOT/pages/deployment/docker/docker-setup.adoc
=> Enhanced Docker Orchestration

modules/ROOT/pages/deployment/docker/docker-setup.adoc
Language review and a note on Helm charts.
=> Review docker setup

modules/ROOT/pages/deployment/docker/docker-setup.adoc, modules/ROOT/pages/deployment/general/general-info.adoc
Add Data Persistence to Docker and the different methods used, Adding a note for macOS users.
=> Add Data Persistence to Docker

modules/ROOT/pages/deployment/container/container-setup.adoc
Fixes the macOS component and some more items
=> Fix the macOS component and more

modules/ROOT/partials/nav.adoc
The security navigation item needed a fix.
=> Fix security navigation

modules/ROOT/pages/index.adoc
=> Small fix to the introduction page

modules/ROOT/pages/deployment/kubernetes/kubernetes.adoc
oCIS setup with minikube and Helm charts improved.
=> Kube clarifications

modules/ROOT/pages/deployment/container/container-setup.adoc
=> No content change, add fixme hints only

modules/ROOT/pages/deployment/kubernetes/kubernetes.adoc
=> Minor Kubernetes fixes

modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/quickguide/quickguide.adoc, modules/ROOT/partials/nav.adoc
Add a quick up and running guide.
=> Add a quick guide

modules/ROOT/pages/deployment/extensions/extensions.adoc
As the title says, language review required.
=> Adding content to the extension landing page

modules/ROOT/pages/deployment/extensions/extensions.adoc
=> mini text fix

modules/ROOT/pages/deployment/extensions/appprovider.adoc, modules/ROOT/pages/deployment/extensions/audit.adoc, modules/ROOT/pages/deployment/extensions/webdav.adoc, modules/ROOT/partials/nav.adoc, site.yml
Adding first extensions based on a template.
=> first adds of extensions

modules/ROOT/attachments/architecture/ocis-c4-model.dsl
@mmattel Here is a useable system landscape view.
=> update c4 model, first useable system landscape view

modules/ROOT/pages/architecture/architecture.adoc
As the title says,
already on staging
=> small fix on the c4 model

modules/ROOT/pages/deployment/general/general-info.adoc
Updates the user creation documentatin based on changes when the recently implementation of the new IDM.
Language review necessary.
=> Update admin and demo user creation

modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/quickguide/quickguide.adoc
Updates the binary, quickguide and general-info with respect to ocis init
Language review required.
=> ocis init for binary and more

modules/ROOT/pages/deployment/extensions/extensions.adoc
Some things restructured in the extension description and info added based on changes in ocis
Language review necessary
=> Info added to extension description

modules/ROOT/pages/index.adoc, modules/ROOT/partials/nav.adoc
Commented the fairly empty configuration section and links in the introduction to sections removed for now.
=> Removed unfinished elements

modules/ROOT/pages/deployment/extensions/auth-bearer.adoc
As the title says, already on staging.
=> Add a first intro text to auth bearer

modules/ROOT/pages/deployment/extensions/extensions.adoc
=> Add curly braces to extension intro

modules/ROOT/pages/deployment/container/container-setup.adoc, modules/ROOT/pages/deployment/extensions/extensions.adoc, modules/ROOT/partials/nav.adoc
=> added keycloak container stack as example

modules/ROOT/pages/index.adoc
=> Explanation for all the ocis variables and comments mentioning oCIS

modules/ROOT/pages/deployment/index.adoc
As the title says, already on staging
=> Remove consecutive mentioning of Infinte Scale

modules/ROOT/pages/deployment/index.adoc
As the title says, already on staging.
=> Container only, remove Docker

modules/ROOT/pages/deployment/container/container-setup.adoc, modules/ROOT/pages/deployment/container/orchestration.adoc
Referencing: https://github.com/owncloud/docs-ocis/pull/155 (Docker-Compose moved to new Orchestration chapter)
@EParzefall FYI
=> Fix missing attributes

modules/ROOT/pages/deployment/container/orchestration.adoc
=> fix rendering issues in orchestration.adoc

modules/ROOT/pages/deployment/extensions/extension_rules.adoc
As the title says,
already on staging
=> Resize an image in the extension rules document

modules/ROOT/pages/architecture/architecture.adoc, modules/ROOT/pages/deployment/configuration/index.adoc, modules/ROOT/pages/deployment/configuration/ocis-config.adoc, modules/ROOT/pages/deployment/container/orchestration.adoc, modules/ROOT/pages/migration/index.adoc
=> some product names correct

site.yml
Just a minor fix to correct the ocis version.
=> Fix the real product version

modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/quickguide/quickguide.adoc, site.yml
This PR fixes the beta download link.
References: https://github.com/owncloud/docs/pull/4738
=> Fixing the Beta Download Link

modules/ROOT/pages/quickguide/quickguide.adoc
Just a small text fix for the quick guide
=> quick guide text fix

modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/deployment/container/container-setup.adoc, modules/ROOT/pages/deployment/general/general-info.adoc
This updates the documentaion with regards to the `ocis init` command.
* general info
* binary setup
* container setup
Language review welcomed 😃
=> Add more details to the ocis init command

site.yml
As the title says, this PR is only necessary for this branch when we do local testing. Should be in sync with docs.
=> Set ocis to beta 2

modules/ROOT/pages/deployment/extensions/ocdav.adoc
=> Text and typo fixes

site.yml
Updates the attribute for ocis beta 3
Merging when we get the ok from @micbar
=> Prepare for ocis beta 3

modules/ROOT/pages/architecture/architecture.adoc, modules/ROOT/pages/deployment/extensions/ocdav.adoc
Reva was not optimal described. Moving some text blocks and adding some stuff fixes this.
=> Adding a better reva description

modules/ROOT/pages/deployment/services/services_rules.adoc
Fixes: #212 (Document new startup env OCIS_EXCLUDE_RUN_SERVICES)
=> Add description for OCIS_EXCLUDE_RUN_SERVICES

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/deployment/services/storage-users.adoc
Fixes: https://github.com/owncloud/docs-ocis/issues/211 (Document new command line for listing and cleaning up expired uploads)
* Minor text fixes and improvements
* Adding a description how to manage incomplete uploads
=> Manage incomplete uploads

modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-1.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-2.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-3.adoc
Fixing some broken xrefs found while testing antora 3.1
=> Fix some xrefs

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Fixed some typos and smoothed the language.
=> typos in orchestration file

site.yml
We can already merge this as it is this repo only and does no harm when early merging.
=> Prepare for ocis beta.7

site.yml
We need to provide the server versions and replace server by webui.
Part of the antora 3.1 upgrade tests.
=> fix some issues in site.yml

site.yml
This PR can safely be merged even beta.8 is not out, the change is only relevant for this repo.
=> Upgrade to beta.8

modules/ROOT/pages/deployment/services/notifications.adoc
Update the notification service description
@kobergj fyi
=> Update the notification service description

modules/ROOT/examples/deployment/container/orchestration/email-notification-tab-1.yaml, modules/ROOT/examples/deployment/container/orchestration/email-notification-tab-2.yaml, modules/ROOT/examples/deployment/container/orchestration/email-notification-tab-3.yaml, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
update changes for https://github.com/owncloud/ocis-charts/pull/86
=> update email configuration and secrets for the ocis helm chart

modules/ROOT/pages/deployment/services/storage-users.adoc
it is 
ocis storage-users uploads clea**n**
not:
~ocis storage-users uploads clear~
=> clean, not clear

modules/ROOT/pages/prerequisites/prerequisites.adoc
This PR improves a little grammar and min version required for NFS Utils
Part of: https://github.com/owncloud/ocis/issues/4595
=> [docs-only]Improve the documentation for NFS share prerequisites

modules/ROOT/pages/security/security.adoc, modules/ROOT/partials/nav.adoc
Fixes: https://github.com/owncloud/docs-ocis/issues/249 (Add a page describing the security measures of ocis)
Add a Security Aspects page
@C0rby pls have a look if the content is correct from your POV. It was originally taken from your paper and adopted slightly.
@micbar fyi
=> Add a Security Aspects page

modules/ROOT/pages/security/security.adoc
As the title says, just a view text improvements
=> Text improvements of the security aspects document

modules/ROOT/pages/deployment/general/general-info.adoc
Fixes: #248 (Document the impact of the location of the ocis data folder)
Note that the data path description will moste likely be extended as we have identified issues relevant to it.
The ocis init command needs a note too, but needs the above prep upfront.
@micbar
=> Notes about the location of the data directory

modules/ROOT/examples/deployment/container/orchestration/nginx-ingress-tab-1.yaml, modules/ROOT/examples/deployment/container/orchestration/nginx-ingress-tab-2.yaml, modules/ROOT/examples/deployment/container/orchestration/nginx-ingress-tab-3.yaml, modules/ROOT/examples/deployment/container/orchestration/values-overwrite-tab-1.yaml, modules/ROOT/examples/deployment/container/orchestration/values-overwrite-tab-2.yaml, modules/ROOT/examples/deployment/container/orchestration/values-overwrite-tab-3.yaml, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Tried to deploy oCIS using K8s as per the documentation testing: https://github.com/owncloud/ocis/issues/4595.
Found some invalid commands and step orders. Also, did some yaml formatting
=> Fix and improve docs: oCIS deployment in K8s

modules/ROOT/pages/deployment/general/general-info.adoc
Add ocis search index command at General Info.
@aduffeck fyi
=> Add ocis search index command

modules/ROOT/pages/prerequisites/prerequisites.adoc
Add Android to the list
Issue see #209
=> Update client info

modules/ROOT/pages/deployment/nfs/nfs.adoc
Above we mention that we support only NFS4 and we don't have to explain previous versions
=> Removing 3

modules/ROOT/pages/deployment/general/general-info.adoc
A documentation how to reset the admin password was missing - fixed.
@ScharfViktor fyi
=> Add how to reset the admin password

modules/ROOT/pages/deployment/services/thumbnails.adoc
Adoption of https://github.com/owncloud/ocis/pull/4737 (add a readme file for the thumbnails service)
=> Thumbnail description

modules/ROOT/pages/deployment/general/general-info.adoc
Just a small change for ease finding the ports used.
Link general info --> services
=> Link default ports for ease of finding

modules/ROOT/pages/deployment/services/nats.adoc
References: https://github.com/owncloud/ocis/pull/4909 (Readme for Nats service)
=> Adding a NATS service description

modules/ROOT/pages/deployment/services/webdav.adoc
References: https://github.com/owncloud/ocis/pull/4912 (Readme for Webdav service)
=> Add WebDav service description

modules/ROOT/pages/deployment/services/proxy.adoc
References: https://github.com/owncloud/ocis/pull/4911 (add proxy README)
=> Add description for the Proxy service

modules/ROOT/pages/deployment/services/frontend.adoc
References: https://github.com/owncloud/ocis/pull/4950 ([docs-only] add frontend readme)
=> Add frontend service description

modules/ROOT/pages/deployment/services/auth-basic.adoc
References: https://github.com/owncloud/ocis/pull/4919 (Readme for Auth-Basic)
=> Add Auth-Basic service description

modules/ROOT/examples/deployment/container/orchestration/service-monitor-tab-1.yaml, modules/ROOT/examples/deployment/container/orchestration/service-monitor-tab-2.yaml, modules/ROOT/examples/deployment/container/orchestration/service-monitor-tab-3.yaml, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
needs https://github.com/owncloud/ocis-charts/pull/95
=> add prometheus / metrics scraping documentation

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/services/logging.adoc
Fixes two things:
* Introduced with #287 we added a glitch that is fixed now
* Improved the X-Request-ID text
=> Improve the X-Request-ID at the logging section

antora.yml
Just added a text note to keep things in mind when changing
=> Add a note in antora.yaml

modules/ROOT/pages/deployment/services/env-var-note.adoc
Improving and updating the env var notes.
=> Improve env var notes

modules/ROOT/pages/configuration/office-integration.adoc
This updates the office integration page to make it better readable.
=> Update the office integration page

modules/ROOT/pages/deployment/binary/binary-setup.adoc
Fix the target location and rename "link"
=> Small fix to the binary setup

modules/ROOT/pages/prerequisites/prerequisites.adoc
There are news regarding apps and clients that need reflection in the documentation.
@michaelstingl fyi
=> Update the prerequisite page for apps and clients

modules/ROOT/examples/deployment/container/orchestration/generic-configs-tab-1.yaml, modules/ROOT/examples/deployment/container/orchestration/generic-configs-tab-2.yaml, modules/ROOT/examples/deployment/container/orchestration/generic-configs-tab-3.yaml
fixes https://github.com/owncloud/docs-ocis/issues/320
=> remove type from ConfigMap

modules/ROOT/pages/deployment/services/s-list/idm.adoc
The notes needed an improvement for better readability of the items addressed.
=> Improve readbility at IDM notes

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/ports-used.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/ocdav.adoc, modules/ROOT/pages/deployment/services/s-list/webdav.adoc
Fixes broken internal links found via htmltest.
=> Fix broken (internal) links

modules/ROOT/pages/deployment/general/ocis-init.adoc
This is a revision of the `ocsi init` command post a discussion with @kobergj and superceds #330 
The build has been pushed to staging to get an impression.
@kobergj pls comment if ok or more changes are needed.
Language review welcomed 😄
=> Revision of the ocis init command

modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/examples/small-scale.adoc, modules/ROOT/partials/deployment/dependent_startup.adoc, modules/ROOT/partials/deployment/nginx_example.adoc, modules/ROOT/partials/deployment/nginx_harden_ssl.adoc, modules/ROOT/partials/deployment/systemd.adoc, modules/ROOT/partials/nav.adoc
We have received some direct feedback that our documentation is missing some crucial steps and that people had some troubles setting up oCIS.
Also some "implicit" feedback showed that our setup documentation is too separated and/or duplicated in multiple places. (owncloud.dev, doc.owncloud.com). This is an attempt to give a simple, easy to follow, mostly copy/pastable guide on how to setup oCIS.
When following this one should be able to have oCIS running in about 10-15 Minutes.
Inspiration came from https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html
=> write a complete setup guide for ocis with system

modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/examples/small-scale.adoc, modules/ROOT/partials/deployment/nginx_example.adoc, modules/ROOT/partials/deployment/nginx_harden_ssl.adoc
Small update to #327 
* fixing ssl to avoid double entries
* forgot to use attributes in the nginx example
* make a command appear separate than together (no content change but copy paste relevant)
=> Small update to the "small scale with systemd" page

modules/ROOT/pages/deployment/services/deployment-considerations.adoc, modules/ROOT/partials/nav.adoc
Fixes: #300 (document service limits (HA / scalability) )
Add a new page covering deployment considerations for services.
@wkloucek pls have a look. Note that we can always add/change stuff but at least we have started.
=> New page: Deployment Considerations (for services)

modules/ROOT/pages/conf-examples/ext-files/wopiserver.adoc, modules/ROOT/pages/conf-examples/office-integration.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc
Addon to #340
This PR adds MS Office to WOPI. It needs special care and is in alignment how we do it in ownCloud Server.
@micbar @dragotin
=> Add MS Office to WOPI

modules/ROOT/pages/maintenance/restore.adoc, modules/ROOT/partials/nav.adoc
Fixes: #208 
References: #353 
Add a restore description.
=> Add a first restore description

modules/ROOT/pages/maintenance/backup.adoc, modules/ROOT/pages/maintenance/restore.adoc
This updates the recently merged backup and restore documents with more info.
Currently visible on stagingg.
=> Update backup and restore

modules/ROOT/pages/deployment/general/general-info.adoc
in General Info: `blob` --> `blobs`
=> Just fixing a plural issue

modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc
Although the service is called postprocessing, the process/action is spelled with a hypen: post-processing.
=> consistency review

modules/ROOT/pages/deployment/binary/binary-setup.adoc
added https:// since it doesn't happen automatically in all browsers
=> added https://

modules/ROOT/pages/conf-examples/office-integration.adoc
Relates to #369 (Add hardware sizing to the Office documentation)
Missed fixing a headline...
=> Fix headline

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
The "manage unfinished upload commands" was hard to read, this is now much better
=> Improvement to the storage-user service description

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/maintenance/b-r/backup.adoc, modules/ROOT/pages/maintenance/b-r/restore.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/partials/nav.adoc
As we are getting more commands to maintain Infinite Scale, I created a new page that collects them all. Some movement of content was necessary. Also some content was fixed and improved for better readability. Note that some new commands are in the pipeline in the ocis repo which makes it now much easier to collect and organize them here.
=> Add a new commands page and do some fixing/improvements

modules/ROOT/pages/deployment/services/s-list/webfinger.adoc
=> removing wrong space

modules/ROOT/pages/deployment/services/s-list/web.adoc
Referencing: https://github.com/owncloud/ocis/pull/5574 ([docs-only] add a small README for the web service)
Adding a description for the web service.
=> Update the web service description

modules/ROOT/pages/deployment/services/s-list/graph.adoc
References: https://github.com/owncloud/ocis/pull/5533 (graph: Initial support for $filter in /users)
Adding that we now can filter.
=> Update graph service using filter

modules/ROOT/pages/architecture/architecture.adoc
Fixes: #384 (Broken link to spaces dev guide)
* Fixes a broken link
* Improves the description text
=> Fix spaces link to dev-docs

modules/ROOT/pages/deployment/services/s-list/idp.adoc
References: https://github.com/owncloud/ocis/pull/5622 ([docs-only] Add README for idp service)
=> Add a description for the IDP service

modules/ROOT/pages/prerequisites/prerequisites.adoc
Two tables in prereqisites needed a fix to render correctly.
=> Fix tables in prerequisites

modules/ROOT/pages/depl-examples/small-scale.adoc
Make it more clear that setting the correct `OCIS_URL` is essential.
Based on the discussion in [talk](https://talk.owncloud.com/channel/infinitescale?msg=RZrn2hzNx5MRbCbzp).
=> Update small scale deployment

modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/pages/prerequisites/prerequisites.adoc
=> Small fixes

modules/ROOT/pages/deployment/services/s-list/idp.adoc
Add a note that the IDP service can only be accessed via https.
=> The IDP service can only be accessed via HTTPS

modules/ROOT/pages/deployment/services/s-list/proxy.adoc
References:
https://github.com/owncloud/ocis/pull/5878 ([docs-only] proxy: update README with notes about role assignment)
Updates the proxy service with recent changes from the ocis repo.
=> Update the proxy service

modules/ROOT/pages/deployment/services/s-list/antivirus.adoc, modules/ROOT/partials/nav.adoc
References: https://github.com/owncloud/ocis/pull/5846 (Antivirus)
This PR adds the antivirus service.
Merge only after the referenced ocis PR has been merged - set to draft to avoid accidentially merging.
=> Add the antivirus service

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
This PR adds some documentation paragraph how to access Minikube on MacOS
=> Added paragraph about access to Minikube on MacOS

modules/ROOT/pages/architecture/architecture.adoc
Fixes #424 (Improve Spaces description)
This PR improves the spaces description.
To be updated when more functionalities like policies and other things are implemented.
=> Update spaces description

modules/ROOT/pages/additional-information/knowledge-base.adoc
Fixes: https://github.com/owncloud/ocis/issues/5961 (2-Factor Authentication 2FA)
Add a KB article with links how to do Two-Factor Authentication with Keycloak
@micbar @dragotin fyi
=> Add KB Two-Factor Authentication with Keycloak

modules/ROOT/pages/prerequisites/prerequisites.adoc, modules/ROOT/pages/prerequisites/xattrs.adoc
With PR #444 (New metadata backend) I forgot to move the attributes to the new page - fixed.
=> Fix missing attributes (moved to new page)

modules/ROOT/pages/deployment/services/s-list/frontend.adoc
Fixes: #459 (Add capabilities to indicate attributes that are read-only)
=> Add Read Only Attributes (frontend service)

modules/ROOT/pages/deployment/services/s-list/notifications.adoc
References: https://github.com/owncloud/ocis/pull/6147 (The email HTML templates added)
The email templating got an update in the ocis repo.
=> Update notifications service email description

modules/ROOT/pages/conf-examples/office/office-integration.adoc, modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/deployment/container/container-setup.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/security/security.adoc, modules/ROOT/pages/deployment/webui/webui-customisation.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc
consistent spelling of web UI as two "words"
=> web UI spelling fixes

modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
References: https://github.com/owncloud/ocis/pull/6282 (Postprocessing Store)
* Adding store to the postprocessing service
* Minore postporcessing fixes
* Removing a unnecessary blank in some services that use caching/storing.
Only merge when the references PR got merged!
=> Add store to postprocessing

modules/ROOT/pages/deployment/services/s-list/search.adoc
References: https://github.com/owncloud/ocis/pull/6304 ([docs-only ]Update search README.md)
Add how to use the tika container.
=> Update Tika container usage (search service)

modules/ROOT/pages/deployment/services/caching.adoc
=> Clarify content in the caching description

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
to be merged after https://github.com/owncloud/ocis-charts/pull/288
=> update latest ocis helm chart to ocis 3.0.0-rc.4

modules/ROOT/pages/deployment/services/s-list/search.adoc
References: #6370 (Add Fulltextsearch Capability)
A new envvar has been added that needs extra mentioning in the search service.
=> Update search when using Tika

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/quickguide/quickguide.adoc, site.yml
Attribute cleanup.
Merge only after [Set the Infinite Scale Versions in ocis-releases.adoc](https://github.com/owncloud/docs/pull/4843) has been merged.
=> Update and cleanup of attributes

modules/ROOT/pages/deployment/container/orchestration/tab-pages/breaking-changes.adoc
Just a small fix for #523
The breaking change value should be true not false
=> Fix HC breaking change value

modules/ROOT/pages/migration/upgrading-ocis.adoc
Another rendering fix in the upgrade guide making the items listed appear identical.
=> Another rendering fix

modules/ROOT/images/architecture/infinite_scale_data_platform.svg
`Singe` -->`Single`
@d7oc fyi and thanks for catching
=> Fix typo in svg image

modules/ROOT/pages/migration/upgrading-ocis.adoc
References: https://github.com/owncloud/ocis/issues/6518
This adds some important info when upgrading to messagepack.
@flamingm0e many thanks providing the details.
@kobergj fyi
=> Update the upgrade guide with more messagpack related info

modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/services.adoc
This adds tables for services per release added.
Note that the texts have been copied from the individual services.
@mfeilner fyi
=> Add table with service per release

modules/ROOT/partials/deployment/nginx_proxy_example.adoc
Fixes: #549 (Update bare metal deployment (nginx part))
Add some necessary proxy directives to the nginx configuration based on user feedback.
=> Update the nginx config

modules/ROOT/pages/deployment/services/s-list/nats.adoc
Fixing a Freudian slip 🤦‍♂️ 
@individual-it thanks for catching
=> Update nats.adoc (fix typo)

modules/ROOT/pages/deployment/services/s-list/idp.adoc
=> Make a text in the IDM service IMPORTANT to make it an eye catcher

modules/ROOT/pages/deployment/services/s-list/userlog.adoc
Fixes: #563 (Decommission Notification (userlog service))
Adds the description for decommissioning.
Note that the text was already reviewed in the ocis repo...
=> Add Deprovisioning

modules/ROOT/pages/maintenance/commands/rebuild-jsoncs3-indexes.adoc
References: #586
Updates the command help output
=> Update the help output of command

modules/ROOT/pages/migration/upgrading-ocis.adoc, modules/ROOT/pages/migration/upgrading_3.0.0_4.0.0.adoc
References #594 (Add migration and Breaking Changes)
Add the deprecated envvars to the breaking change description.
@tbsbdr fyi
=> Add deprecated envvars to breaking changes

modules/ROOT/pages/migration/upgrading-ocis.adoc
Same entry is in breaking changes where it belongs to.
=> Removing a double present list item entry

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc
Small fix for the creation of the `compose_tab_3` url.
A classic copy/paste error... 🤦‍♂️
=> Fix the creation of the compose_tab_3 url

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
This PR adds more context about docker compose version 2 and the fact that will be a plugin of docker in the future with the appropriate CLT change.
=> Added more context about Docker compose version 2

modules/ROOT/pages/maintenance/b-r/backup.adoc
There were some good comments from sales leading to improve the backup documentation.
=> Improve the backup description based on a comment from sales

modules/ROOT/pages/migration/upgrading_3.0.0_4.0.0.adoc
Based on a comment in the talk channel, I updated the `ocis migrate decomposedfs` with a better and clearer description improving user experience.
=> Explain the ocis migrate decomposedfs in more details when upgrading

modules/ROOT/pages/deployment/services/s-list/ocs.adoc
References: #613 (Auto-Accept shares)
This adds the description for the ocs service.
=> Add ocs service description

modules/ROOT/pages/deployment/services/s-list/frontend.adoc
Fixes: https://github.com/owncloud/docs-ocis/issues/613 (Auto-Accept shares)
Add the documentation about the upcoming auto-accept share feature.
=> Auto-Accept Shares

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
See also https://github.com/owncloud/ocis-charts/issues/395
blocked by https://github.com/owncloud/ocis-charts/issues/395#issuecomment-1722877069
=> minikube configurations for mac

modules/ROOT/pages/depl-examples/bare-metal.adoc
Superceding: #625 (Update bare-metal.adoc)
Improve the commands and description to reload the webserver configuration.
=> Update the Nginx and Apache2 commands in bare metal deployment

modules/ROOT/pages/deployment/services/ports-used.adoc, modules/ROOT/pages/deployment/services/s-list/auth-basic.adoc, modules/ROOT/pages/deployment/services/s-list/auth-bearer.adoc, modules/ROOT/pages/deployment/services/s-list/auth-machine.adoc, modules/ROOT/pages/deployment/services/s-list/auth-service.adoc, modules/ROOT/partials/deployment/services/auth-service-family.adoc, modules/ROOT/partials/nav.adoc
Fixes: #592 (New service: auth-service)
Add the `auth-service` Service.
Note the text is taken from the ocis PR (see reference).
=> Add the auth-service Service

modules/ROOT/pages/deployment/services/ports-used.adoc, modules/ROOT/pages/deployment/services/s-list/sse.adoc, modules/ROOT/partials/nav.adoc
Fixes: #595 (New service: sse)
Adds the new `SSE` service.
=> Add SSE service

modules/ROOT/pages/deployment/services/ports-used.adoc, modules/ROOT/pages/deployment/services/s-list/ocm.adoc, modules/ROOT/partials/nav.adoc
Fixes: #651 (New Service: OCM)
Adds the new OCM service to teh documentation.
=> Add the OCM service

modules/ROOT/pages/deployment/services/s-list/ocm.adoc
As the title says, note that this is also wrong in the dev docs (copied from) and needs to be fixed there too.
=> Just a small typo fix in OCM

modules/ROOT/pages/architecture/architecture.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc
Some images were too big, resizing. Clicking on it anyways shows them full.
=> Resize some images

README.md
References: #667 
This block was missing in readme, added.
=> add missing block in readme

modules/ROOT/pages/deployment/services/s-list/gateway.adoc
References: https://github.com/owncloud/ocis/pull/7977 ([docs-only] Update Gateway Readme)
New we have a intro text what the gateways service is about.
Note that this only changes the intro text.
An additional issue will be filed to address the caching changes - as they are for 5.0 only.
=> Update gateway purpose description

docs/new-version-branch.md
Just a small internal link fix + enable internal docs for branching (upcoming)
=> Just a small internal link fix + enable internal docs for branching

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc, site.yml
Some small fixes to ease versioning
=> Some small fixes to ease versioning

es-docker-compose.yml
Add ES example yml for ease of testing
=> Add ES example yml

modules/ROOT/pages/deployment/services/env-var-changes.adoc, modules/ROOT/partials/deployment/services/general-info/env-var-changes/added-4.0.5-5.0.0.adoc, modules/ROOT/partials/nav.adoc
=> [5.0] [PR 713] Added a page with changed envvars based on the version

antora.yml
This was accidentally set to the same values as 5.0 - fixed.
No backport to 5.0
=> Fix antora.yml for master

docs/new-version-branch.md, ext-antora/generate-index.js
Script update for consistency + small fixes.
Backport to 4.0 and 5.0
=> ES index update

docs/new-version-branch.md, ext-antora/generate-index.js
=> [5.0] [PR 722] ES index update

docs/new-version-branch.md, ext-antora/generate-index.js
=> [4.0] [PR 722] ES index update

modules/ROOT/pages/deployment/services/env-var-note.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc
=> [5.0] [PR 726] Add envvars to yaml config

modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/multi-location/caching-list.adoc
=> [5.0] [PR 728] Make local/global envvars in caching more clear

modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/deployment/general/general-info.adoc
=> [5.0] [PR 732] Update the General Info page with $HOME and ~ for config and data dir

modules/ROOT/pages/deployment/services/caching.adoc, modules/ROOT/pages/deployment/services/s-list/antivirus.adoc, modules/ROOT/pages/deployment/services/s-list/audit.adoc, modules/ROOT/pages/deployment/services/s-list/clientlog.adoc, modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/notifications.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/search.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/deployment/services/s-list/sharing.adoc, modules/ROOT/pages/deployment/services/s-list/sse.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/multi-location/caching-list.adoc, modules/ROOT/partials/multi-location/event-bus.adoc
=> [5.0] [PR 734] Update caching and persistence

modules/ROOT/pages/prerequisites/prerequisites.adoc
Add char encoding: UTF8 mb4 and no caping of IOPS as requirements.
=> Add char encoding and IOPS requirements

modules/ROOT/pages/prerequisites/prerequisites.adoc
Add char encoding: UTF8 mb4 and no caping of IOPS as requirements.
=> [backport] Add char encoding and IOPS requirements

modules/ROOT/pages/deployment/services/s-list/ocs.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/store.adoc
=> [5.0] [PR 740] Make store service configurable

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/maintenance/space-ids/space-ids.adoc, modules/ROOT/partials/multi-location/caching-list.adoc, modules/ROOT/partials/nav.adoc
=> [5.0] [PR 745] Updating the storage-users service description

modules/ROOT/pages/migration/upgrading-ocis.adoc, modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc
=> [5.0] [PR 747] Migration guide update because of resharing changes

modules/ROOT/pages/deployment/general/general-info.adoc
=> [5.0] [PR 752] Fix ocis base data path for binary

modules/ROOT/pages/deployment/webui/webui-customisation.adoc
Fixes: #743 (Add changes to the web service)
This adds the changes for web app added in ocis master.
Note that after content clarification with @fschade, we need to fix the web/readme in the ocis repo too.
Currently visible on [staging](https://doc.staging.owncloud.com/ocis/next/deployment/webui/webui-customisation.html)
No backport
=> WebUI customisation update

modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc
=> [master] [PR 756] Update upgrading_4.0.0_5.0.0.adoc

modules/ROOT/pages/deployment/binary/binary-setup.adoc
=> [5.0] [PR 755] Fixing another $HOME usage

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/logging.adoc, modules/ROOT/partials/multi-location/idm-https-reverse-proxy.adoc
=> [5.0] [PR 760] Update binary installation and related documents

modules/ROOT/pages/deployment/services/s-list/app-registry.adoc
=> [5.0] [PR 647] Update the app registry service description

modules/ROOT/pages/deployment/services/s-list/app-registry.adoc
=> [4.0] [PR 647] Update the app registry service description

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc
=> [5.0] [PR 769] Update envvar and yaml use description

modules/ROOT/pages/deployment/services/s-list/frontend.adoc
=> [5.0] [PR 777] Update the frontend description to improve password management

modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc, site.yml
=> [5.0] [PR 783] Fix for docker pull in upgrade to print the correct version

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/storage/general-considerations.adoc, modules/ROOT/pages/deployment/storage/s3.adoc
=> [5.0] [PR 785] Fix S3 and Storage

modules/ROOT/pages/deployment/services/s-list/proxy.adoc
=> [5.0] [PR 787] Small change to the proxy service documentation

modules/ROOT/pages/deployment/services/s-list/frontend.adoc
=> [5.0] [PR 789] Describe allow disabling the password policy

modules/ROOT/pages/deployment/storage/general-considerations.adoc
=> [5.0] [PR 791] Fixing the NFS storage table

site.yml
=> [5.0] [PR 797] Update site.yml for local building only

antora.yml
Just a minor fix missed in the last version change.
=> Missed one entry to fix the latest version in the 5.0 branch

modules/ROOT/pages/deployment/general/general-info.adoc
=> [5.0] [PR 809] Fix typo in general-info.adoc

modules/ROOT/pages/deployment/binary/binary-setup.adoc
=> [5.0] [PR 810] Fix ps command in binary description

modules/ROOT/pages/deployment/services/s-list/ocm.adoc
Same as https://github.com/owncloud/ocis/pull/8931
=> Fix: ocmproviders.json in ocm.adoc

modules/ROOT/pages/deployment/services/s-list/ocm.adoc
=> [5.0] [PR 806] Fix: ocmproviders.json in ocm.adoc

modules/ROOT/pages/deployment/binary/binary-setup.adoc
=> [5.0] [PR 805] Fix: Remove mDNS from binary-setup.adoc ?

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/general/ocis-init.adoc, modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/partials/multi-location/event-bus.adoc, modules/ROOT/partials/multi-location/idm-https-reverse-proxy.adoc, modules/ROOT/partials/nav.adoc
=> [5.0] [PR 817] Fix the Bare Metal deployments

modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc, modules/ROOT/pages/deployment/general/general-info.adoc
all we write is American English.
=> spell initialisation -> initialization

modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc, modules/ROOT/pages/deployment/general/general-info.adoc
=> [5.0] [PR 821] spell initialisation -> initialization

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/s-list/idm.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc, modules/ROOT/partials/multi-location/compose-version.adoc
Fixes: https://github.com/owncloud/ocis/issues/9047 (Reseting password via cli doesn't work)
The reset admin password description was incomplete, misleading and contained a wrong statement.
=> Reset Admin Password

modules/ROOT/pages/deployment/general/general-info.adoc
=> [5.0] [PR 827] Reset password fix for docker compose

modules/ROOT/pages/deployment/general/general-info.adoc
This is just a minor text fix / improvement for the reset admin pwd docs.
With merging, we also trigger the new UI for code blocks.
=> Text update resetpassword from feedback.

modules/ROOT/pages/deployment/general/general-info.adoc
=> [5.0] [PR 829] Text update resetpassword from feedback.

modules/ROOT/pages/deployment/general/general-info.adoc
=> [5.0] [PR 831] Render fix in the general-info page

modules/ROOT/pages/deployment/general/general-info.adoc
=> [5.0] [PR 833] Clarify text for reset admin passwd

.drone.star
=> [5.0] [PR 835] chore: report CI result to builds channel

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/monitoring/prometheus.adoc
=> [5.0] [PR 842] Add text how to manually define which services will be started

ext-antora/generate-index.js
=> [5.0] [PR 857] Fix command typo in generate-index.js

modules/ROOT/pages/maintenance/b-r/backup_considerations.adoc, modules/ROOT/partials/nav.adoc
=> [5.0] [PR 859] Backup Considerations

README.md, modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/deployment/services/log-service-ecosystem.adoc, modules/ROOT/partials/multi-location/caching-list.adoc
This is a partial backport of #866 but without changes related to the activitylog service
=> Partial backport of #866

modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/sharing.adoc
=> [5.0] [PR 892] Make banned passwords usecase more visible

modules/ROOT/pages/deployment/services/services.adoc
=> [5.0] [PR 896] Add that no services have been added in ocis v4

modules/ROOT/pages/deployment/services/services.adoc
=> [4.0] [PR 896] Add that no services have been added in ocis v4

antora.yml, modules/ROOT/pages/index.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc, site.yml
=> [5.0] [PR 895] Enable Rolling Releases in master (next)

antora.yml, modules/ROOT/pages/conf-examples/office/ext-files/app-registry.adoc, modules/ROOT/pages/conf-examples/office/ext-files/docker-compose.adoc, modules/ROOT/pages/conf-examples/office/ext-files/env.adoc, modules/ROOT/pages/conf-examples/office/ext-files/wopiserver.adoc, modules/ROOT/pages/conf-examples/office/office-integration.adoc, modules/ROOT/pages/deployment/container/container-setup.adoc, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/services/env-var-changes.adoc, modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/migration/upgrading-ocis.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc, modules/ROOT/partials/multi-location/compose-version.adoc, modules/ROOT/partials/multi-location/tab-text.adoc
Backport of PR #905
Note that the `antora.yml` values would have been overwritten by the backport, they are back to the values as they should be.
=> [5.0] [PR 905] Refactor attributes used

package.json, yarn.lock
=> [5.0] [PR 909] Antora package.json refactoring

antora.yml, modules/ROOT/pages/conf-examples/office/office-integration.adoc, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc
This PR cleans up more attributes used on multiple locations.
=> Cleanup more attributes

antora.yml, modules/ROOT/pages/conf-examples/office/office-integration.adoc, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc
=> [5.0] [PR 915] Cleanup more attributes

modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc, modules/ROOT/partials/multi-location/idm-https-reverse-proxy.adoc
=> [5.0] [PR 920] Fix missing special envvars

site.yml
References: #907 (Prepare for ocis 5.0.6)
For local building only.
Only merge after #907 has been merged.
=> Update local site.yml for 5.0.6

site.yml
=> [5.0] [PR 908] Update local site.yml for 5.0.6

modules/ROOT/pages/maintenance/commands/backup-consistency.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/pages/maintenance/commands/revisions-cleanup.adoc, modules/ROOT/pages/maintenance/commands/trash.adoc
=> [5.0] [PR 914] Add offline CLI commands to maintenence

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
I suppose that these changes could also be made to the v5 branch.
=> Minor fixes to shared-setup

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
=> [5.0] [PR 928] Minor fixes to shared-setup

site.yml
=> Internal only, update rolling to 6.2.0

modules/ROOT/pages/deployment/services/caching.adoc
A branch that waited a long time to get updated and merged...
=> Container networking pitfalls

modules/ROOT/pages/deployment/services/caching.adoc
=> [5.0] [PR 937] Container networking pitfalls

modules/ROOT/partials/deployment/services/env-and-yaml.adoc
=> [5.0] [PR 938] Fix yaml file name explanation text

modules/ROOT/pages/deployment/general/ocis-init.adoc
=> [5.0] [PR 941] Update ocis.init (prepare for --diff)

modules/ROOT/pages/prerequisites/prerequisites.adoc
- added supported languages
- removed preliminary support notice of spaces feature
=> added supported languages

modules/ROOT/pages/deployment/services/s-list/proxy.adoc
I noticed that "prerequisites" was a typo in #912 
And minor things that my IDE was also pointing out.
=> doc: minor edits to proxy.adoc

modules/ROOT/pages/prerequisites/prerequisites.adoc
=> [master] [PR 946] added supported languages

modules/ROOT/pages/maintenance/commands/commands.adoc
Just some small anchor/link fixes.
No backport, master only.
=> Just some small anchor/link fixes

modules/ROOT/pages/depl-examples/bare-metal.adoc
=> [5.0] [PR 958] Update the bare-metal deployment for better readability

site.yml
Only merge after the rolling release has been published.
=> Local repo only, update ocis to rolling 6.3.0

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Removing only one leftover character
=> Fix one tick too much

antora.yml, modules/ROOT/pages/deployment/webui/webui-customisation.adoc, modules/ROOT/pages/deployment/webui/webui-theming.adoc
Fixes: #933 (Web: Introduce theme processing)
Update the theming page for web.
* Removal of outdated content
* Adding new content
* Add example via include (version proof, if path does not change) 
* Make items in loading application in web-customisation look the same as we have here
No Backport
=> Update Web UI theming

modules/ROOT/pages/deployment/services/s-list/gateway.adoc
=> [5.0] [PR 969] Small gateway service description fix

modules/ROOT/pages/deployment/services/s-list/ocm.adoc
Fixes: #957 (More ocm service readme changes)
Update of the ocm service description.
As there are many more code changes upcoming, this PR will not be the last one 😄 
No backport
=> Update the ocm service description

site.yml
=> [5.0] [PR 976] Local only, ocis 5.0.7

modules/ROOT/pages/deployment/services/s-list/notifications.adoc
=> [5.0] [PR 980] Reordering some text in notifications to improve readability

modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
Based on a discussion with @dragonchaser adding a note that this example is only one instance per deployment.
=> Only one instance per deployment

modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
=> [5.0] [PR 982] Only one instance per deployment

site.yml
=> [5.0] [PR 985] Local only, ocis 6.4.0

modules/ROOT/pages/deployment/services/s-list/collaboration.adoc
Fixes #973 (Update collaboration service readme)
Update the collaboration service, content taken from the referenced PR`s
No backport !
=> Update Collaboration Service

modules/ROOT/pages/maintenance/commands/rolling-back-and-forward.adoc
=> [5.0] [PR 990] fix migration command

modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc, modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Fixes: #986 (Improvements Easy Entry Docs)
This PR fixes _most_ of the items identified from the referenced PR, those have been checkmarked.
The remaining ones either do not make sense or would need to re-document already existing stuff. A reference to the source is enough.
@tbsbdr fyi
=> Update compose deployments based on feedback

modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc, modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
=> [5.0] [PR 992] Update compose deployments based on feedback

antora.yml
This PR makes 5.0.8 default in the 5.0 branch.
=> Make 5.0.8 default in the 5.0 branch

modules/ROOT/pages/deployment/services/s-list/storage-system.adoc
=> [5.0] [PR 1000] Describe the purpose of the storage-system service

modules/ROOT/pages/deployment/general/general-info.adoc
Some render fixes for the general info document.
=> General Info render fixes

modules/ROOT/pages/deployment/general/general-info.adoc
=> [5.0] [PR 1005] General Info render fixes

modules/ROOT/pages/deployment/container/container-setup.adoc
This PR just updates docker command for getting default user and group ID
=> docs: updating docker command for getting user id

modules/ROOT/pages/deployment/container/container-setup.adoc
=> [5.0] [PR 1017] docs: updating docker command for getting user id

modules/ROOT/pages/deployment/services/s-list/antivirus.adoc
Fixes: #1016 (Make antivirus workers configurable)
Add a description for antivirus workers.
No backport
=> Add antivirus workers

site.yml
=> [5.0] [PR 1026] ocis 6.6.1 rolling (local build relevant only)

modules/ROOT/pages/depl-examples/container-setup.adoc, modules/ROOT/partials/nav.adoc
=> [5.0] [PR 1031] Relocate and update the container setup page

modules/ROOT/pages/maintenance/commands/commands.adoc
=> [5.0] [PR 1036] Fix path for cli --basePath parameter

modules/ROOT/pages/additional-information/knowledge-base.adoc, modules/ROOT/pages/deployment/services/s-list/ocs.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc
Fixes: #1045 (Update proxy info (claim update clarification))
Text comes from the referenced issue pointing to an ocis PR
* Add claim update info
* Additionally found two cache related fixes
* Add knowledge base entry
No backport
=> Update proxy service

site.yml
References: https://github.com/owncloud/docs-main/pull/83 (Add ocis 5.0.9 release notes)
=> [master] set ocis 5.0.9 (local build only)

antora.yml
References: https://github.com/owncloud/docs-main/pull/83 (Add ocis 5.0.9 release notes)
=> [5.0] set ocis 5.0.9 (global build)

modules/ROOT/pages/depl-examples/bare-metal.adoc
=> Typo fix in bare-metal.adoc

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
=> [5.0] [PR 1055] Update bare metal deployments

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
Just a few bare metal fixes
* use force in link command
* headline capitalisation fix
=> Small bare metal fixes

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
=> [5.0] [PR 1058] Small bare metal fixes

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
=> [5.0] [PR 1061] Make SMTP_SENDER a mandatory setting

modules/ROOT/pages/deployment/storage/s3.adoc
=> [5.0] [PR 1064] Add that the S3 blob is encrypted automatically on the AWS side

modules/ROOT/partials/deployment/systemd.adoc
=> del_stray_word_ocis_bin_systemd.adoc

modules/ROOT/partials/deployment/systemd.adoc
=> [5.0] [PR 1066] del_stray_word_ocis_bin_systemd.adoc

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Update needed to fix some details.
(Note, Windows drove me nuts...)
=> Update the docker compose deployment example

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
=> [5.0] [PR 1067] Update the docker compose deployment example

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Helps identifying config issues.
=> Add a command to show the final config in compose deployments

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Improve the update section of the compose deployments.
Locally tested, weorks fine.
No backport, v5 has different text
=> Update docker compose update details

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
=> [5.0] [PR 1072] Add a command to show the final config in compose deployments

modules/ROOT/pages/maintenance/space-ids/space-ids.adoc, modules/ROOT/pages/maintenance/user-ids/user-ids.adoc, modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Typo fixes found by @phil-davis and myself
=> Typo fixes

modules/ROOT/pages/maintenance/commands/changed-cli.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/pages/maintenance/commands/shares-cleanup.adoc
Fixes: #1082 (CLI Command: Cleanup stale shares)
Add CLI command `ocis shares cleanup`
Puttining on draft until the ocis PR got merged
=> Add CLI command `ocis shares cleanup`

modules/ROOT/pages/maintenance/commands/revisions-cleanup.adoc
=> [5.0] [PR 1084] Add note about dry-run

modules/ROOT/pages/maintenance/commands/changed-cli.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc
The command was missing in the list
=> Add ocis auth-app create command to the maintenance commands

modules/ROOT/pages/deployment/storage/s3.adoc
Fixes: #1096 (S3 has limits with respect to quantity of parts uploaded)
References: https://github.com/owncloud/ocis/issues/10780 (S3 Improvements)
Add limits to the S3 docs.
=> Update S3 with respect to limits

site.yml
Update the actual/former version and compiled date.
Backport to 7.0
=> Update site.yml with version changes

site.yml
=> [7.0] [PR 1099] Update site.yml with version changes

docs/new-version-branch.md
Update the branch numbers because of a new major release
=> Update new version branch docs

ext-antora/comp-version.js
=> [7.0] [PR 1108] Update antora extension to print component, versions and files

ext-antora/comp-version.js
=> [5.0] [PR 1108] Update antora extension to print component, versions and files

modules/ROOT/pages/deployment/general/ocis-init.adoc
=> [master] [PR 1112] docs: fix typo in deployment general

modules/ROOT/pages/deployment/general/ocis-init.adoc
=> [5.0] [PR 1112] docs: fix typo in deployment general

modules/ROOT/pages/deployment/services/env-var-changes.adoc
=> [7.1] [PR 1116] Fix the delta range for envvars

modules/ROOT/pages/depl-examples/container-setup.adoc
=> [7.1] [PR 1117] Update container-setup.adoc

modules/ROOT/pages/depl-examples/container-setup.adoc
=> [7.0] [PR 1117] Update container-setup.adoc

modules/ROOT/pages/deployment/services/s-list/notifications.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/maintenance/commands/changed-cli.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/pages/migration/upgrading-ocis.adoc, modules/ROOT/pages/migration/upgrading_7.0.0_7.1.0.adoc
=> [7.1] [PR 1119] Changes for 7.1

ext-antora/comp-version.js
=> [7.0] [PR 1130] Update the component-version counting extension

ext-antora/comp-version.js
=> [7.1] [PR 1130] Update the component-version counting extension

docs/new-version-branch.md, docs/the-branching-workflow.md
=> [7.0] [PR 1136] Update the versioning process

antora.yml, modules/ROOT/pages/additional-information/knowledge-base.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/idp.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc, modules/ROOT/partials/multi-location/compose-version.adoc
=> [7.1] [PR 1141] Simplify attribute usage and paths 

modules/ROOT/pages/migration/upgrading_7.0.0_7.1.0.adoc
Removing a remaining but unnecessary sub section.
This was a orphaned sub section item that has been forgotten to be removed.
=> Remove an unecessary sub section line

modules/ROOT/pages/maintenance/m-mode/maintenance-mode.adoc, modules/ROOT/partials/nav.adoc
This text adds an admin description for the upcoming maintenance mode.
Currently no backport planned, this will be published with the next minor release which is 7.2.
@phil-davis a language review is welcomed
=> Maintenance mode

antora.yml, modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc, modules/ROOT/pages/migration/upgrading_2.0.0_3.0.0.adoc, modules/ROOT/partials/multi-location/compose-version.adoc
This PR improves attribute (variable) usage:
* Removal of two attributes
We have an existing replacement that can be reused. In former versions we needed all of them.
* Improved texts
* Improved attribute handling
=> Rework some attributes

antora.yml, modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc, modules/ROOT/pages/migration/upgrading_2.0.0_3.0.0.adoc, modules/ROOT/partials/multi-location/compose-version.adoc
=> [7.1] [PR 1147] Rework some attributes

antora.yml
References: #1148 ([7.1] [PR 1147] Rework some attributes)
The backport UNINTENDED overwrote some attributes that it should not and have not been changed. This drives me nuts...
=> Fix unintended attribute value overwrite in antora.yml by backport

antora.yml, modules/ROOT/partials/multi-location/compose-version.adoc
This PR does more attribute cleanups.
Backport to 7.1 (carfully to avoid overwriting values which should stay...)
=> More attribute cleanups

antora.yml, modules/ROOT/partials/multi-location/compose-version.adoc
=> [7.1] [PR 1150] More attribute cleanups

modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc, modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
The Compose examples needed some text fixes.
=> Some text fixes for the Compose examples

modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc, modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
=> [7.1] [PR 1163] Some text fixes for the Compose examples

modules/ROOT/pages/migration/upgrading_7.1.0_7.2.0.adoc
=> [7.2] [PR 1176] Add changed envvar link to migration document

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
=> [7.2] [PR 1181] Fix storage-users command for resume non virus infected

modules/ROOT/pages/deployment/storage/s3.adoc
=> [7.1] [PR 1187] Change STORAGE_USERS_DRIVER to STORAGE_SYSTEM_DRIVER

modules/ROOT/pages/deployment/storage/s3.adoc
=> [7.2] [PR 1187] Change STORAGE_USERS_DRIVER to STORAGE_SYSTEM_DRIVER
