antora.yml, site.yml
Fixes the printed name of the component `oCis` --> `oCIS`
=> Fix the printed name of the ocis component

modules/ROOT/pages/deployment/nfs.adoc
This PR updates the NFS documentation.
It is more or less a rewrite because we cant reuse the linked version as it contains stuff that does not work or is not needed with oCIS.
Not pushed to staging
=> Updated NFS documentation

modules/ROOT/pages/deployment/index.adoc
Itemize the deployment overview for better readability.
Using Manual instaed of Basic setup to have the same word as it is used for the document name.
=> Itemize text for better readbility

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/manual/manual-setup.adoc, modules/ROOT/partials/nav.adoc, site.yml
During work on manual/docker installation, I identified the need to have a general info document in the deployment section which is not dependent on the way how it is deployed.
Review welcome.
Most likely some content be added with regards to location precedence, waiting for answers from dev. Maybe other stuff will be added too, just a feeling...
Note that there are also changes in the manual installation part (because I started there), but this is definitley not finished. Reviewing this and merging is fine and a good starting point to continue 😄 
Note that heading `=== List Running oCIS Processes` in Manual Installation is also not finished and contains a copy/paste note for the ongoing work that needs refinement, but this will be another PR...
Stuff is already on staging.
=> Add new document: General Info

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/manual/manual-setup.adoc
Moving some stuff from manual install to general info as it can also be used in docker
Note that xref pointing to a heading in the same document does not need to have a written description - it uses the heading text 😃
=> move basic setup

modules/ROOT/pages/deployment/general/general-info.adoc
Remove the account service from the list. When the LibreIDM gets merged in ocis soon, this service will go away
=> Remove the account service from the list

modules/ROOT/pages/deployment/manual/manual-setup.adoc
There was a section misleveling in the manual installation causing the to not to display - fixed
=> Fix toc in manual setup

modules/ROOT/partials/extension_tables/appprovider_configvars.adoc, modules/ROOT/partials/extension_tables/audit_configvars.adoc, modules/ROOT/partials/extension_tables/auth-basic_configvars.adoc, modules/ROOT/partials/extension_tables/auth-bearer_configvars.adoc, modules/ROOT/partials/extension_tables/auth-machine_configvars.adoc, modules/ROOT/partials/extension_tables/frontend_configvars.adoc, modules/ROOT/partials/extension_tables/gateway_configvars.adoc, modules/ROOT/partials/extension_tables/graph-explorer_configvars.adoc, modules/ROOT/partials/extension_tables/graph_configvars.adoc, modules/ROOT/partials/extension_tables/group_configvars.adoc, modules/ROOT/partials/extension_tables/idm_configvars.adoc, modules/ROOT/partials/extension_tables/idp_configvars.adoc, modules/ROOT/partials/extension_tables/nats_configvars.adoc, modules/ROOT/partials/extension_tables/notifications_configvars.adoc, modules/ROOT/partials/extension_tables/ocdav_configvars.adoc, modules/ROOT/partials/extension_tables/ocs_configvars.adoc, modules/ROOT/partials/extension_tables/proxy_configvars.adoc, modules/ROOT/partials/extension_tables/sharing_configvars.adoc, modules/ROOT/partials/extension_tables/storage-metadata_configvars.adoc, modules/ROOT/partials/extension_tables/storage-publiclink_configvars.adoc, modules/ROOT/partials/extension_tables/storage-shares_configvars.adoc, modules/ROOT/partials/extension_tables/storage-users_configvars.adoc, modules/ROOT/partials/extension_tables/store_configvars.adoc, modules/ROOT/partials/extension_tables/thumbnails_configvars.adoc, modules/ROOT/partials/extension_tables/user_configvars.adoc, modules/ROOT/partials/extension_tables/web_configvars.adoc, modules/ROOT/partials/extension_tables/webdav_configvars.adoc
Adding the current known configvar files from extensions contaning known environment variables - as starting point as this all is under heavy development.
Note that these files will be autogenerated in future and will contain actual data.
See:  https://github.com/owncloud/ocis/issues/3583 (Environment variable tables from extensions for admin docs (as includable .adoc file))
When this happens, we will include from external source and get rid of the problem that tables may have outdated content. The files merged here will be removed.
=> Add example configvars files

modules/ROOT/pages/deployment/security/security.adoc, modules/ROOT/partials/nav.adoc
Migration and Maintenance won't be usable before the beta release, therefore not included. Updated demo user deletion in security chapter.
=> Disabled empty sections

modules/ROOT/pages/deployment/container/container-setup.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/partials/deployment/ocis_init.adoc
This fixes the container documentaion with regards to the `ocis init` command recently added.
Note, the binary part and the quick guide will come next.
=> ocis init container

modules/ROOT/pages/deployment/extensions/app-provider.adoc, modules/ROOT/partials/nav.adoc
Renaming the extension `appprovider` --> `app-provider`
References: https://github.com/owncloud/ocis/pull/3665 (approvider -> app-provider)
Note that the yaml file cant be rendered atm because the referenced PR needs merging first. Post merging and on the next docs build, rendering will be fine automatically.
=> Rename the appprovider extension

site.yml
Small fix to add apostrops to an ocis attribute. No harm before but for harmionisation...
=> Add missing apostrophs to attribute

modules/ROOT/pages/deployment/deployment/deployment_examples.adoc, modules/ROOT/partials/nav.adoc
The orchestration documentation is updated:
* Focus on Docker Compose and Kubnernetes - no examples
* Prepare a new section for compose examples - not visible atm
* The content for the new compose stuff is NOT ready for review atm
Already on Staging
=> Update to the orchestartion stuff

modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/quickguide/quickguide.adoc
Fixes: https://github.com/owncloud/docs-ocis/issues/181 (ocis kill no longer exists)
=> Remove the ocis kill command

site.yml
Prepare for the upcoming ocis beta 4
This PR can safely be merged as it ist for this repo only.
The docs version must only be merged when beta.4 is finally out and available.
@micbar fyi
=> prepare_for_ocis_beta4

modules/ROOT/pages/deployment/container/container-setup.adoc
When using `~/path` in docker mount commands, you will get get an error, use `$PWD/path` instead for defining the users home.
=> Fix the use of $PWD vs ~ for docker mount

modules/ROOT/pages/deployment/services/webdav.adoc
Have the text in sync, see linked reference.
=> Fix the webdav description to be in sync with the ocis repo description

antora.yml
Based on renaming extension to services 😄
=> The link to the external URL for including ocis resources has changed

modules/ROOT/pages/deployment/services/services.adoc
Referencing: https://github.com/owncloud/ocis/issues/3793#issuecomment-1173876470 (Open descriptions and defaults for environment variables)
=> Add a description for paths when using container vs binary

modules/ROOT/pages/deployment/services/services_rules.adoc
Referencing: https://github.com/owncloud/ocis/pull/4133 (fix OCIS_RUN_SERVICES)
The env got renamed as part of extensions --> services
@wkloucek fyi
=> Env rename OCIS_RUN_SERVICES

modules/ROOT/pages/deployment/general/general-info.adoc
This just fixes a small typo I ran into while taking a look at the docs.
=> docs (deployment/general): Fix typo

modules/ROOT/pages/deployment/general/ocis-init.adoc, modules/ROOT/partials/nav.adoc
Based on community feedback, the `ocis init` command was not clear.
A new page has been added for a detaild description.
@dragonchaser @wkloucek your feedack/review is very welcomed.
=> Add a ocis init description page

modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/deployment/container/container-setup.adoc, modules/ROOT/partials/deployment/ocis_init.adoc
As the title says, the path printed in the response is different when it comes to binary and container setups.
=> Fix setting the correct path for binary and container ocis init response

antora.yml, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/env-var-note.adoc, modules/ROOT/pages/deployment/services/logging.adoc, modules/ROOT/pages/security/security.adoc, modules/ROOT/partials/nav.adoc
Fixes: #266 (Document the use of log levels -especially the access log)
* Create a logging page embedded into the new service structure
* Create a version independent attribute defining the path to services for xref
* Using that attribute for existing xrefs making it easier to reference
* Adding a link to logging in the general info page
@micbar I took the referenced text and adapted it a little bit but one point is open for me. Maybe we could add more info HOW `X-Request-ID` can be added, in particualr for our webui...
=> Create a logging page

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Fixes: #297 (Docs. Docker-compose section. nonexistent link)
The Docker Compose section needed a rewrite as a referenced source was deleted
I searched for tools to support the creation of docker compose files out of helm charts, but usually you only get it the other way round. We can update the text if a tool is capable supporting that.
@ScharfViktor fyi
=> Update the Docker Compose section

antora.yml, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/val-desc-tab-1.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/val-desc-tab-2.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/val-desc-tab-3.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-1.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-2.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/values-tab-3.adoc, modules/ROOT/pages/deployment/services/services.adoc
References: #298 (Update the Docker Compose section)
Post a discussion with @wkloucek, we need to update the Docker Compose section.
* Adds, in the same way as we do with Helm, tabs which are aligned to releases (tags).
* We use the same tab descriptions for helm and compose (important to avoid confusion about releases!) but use different attributes to include/reference the origin of sources. This enables that the repos ocis-charts and ocis can use different tag names.
* The compose example files did not disappear, the original link was corrected to be one layer above.
* An issue has been created to maintain https://github.com/owncloud/ocis/issues/5040
@wkloucek pls create a README.MD in the ocis examples directory as discussed to avoid accidentially deletion or move without notice to …
=> Update Docker Compose

modules/ROOT/pages/prerequisites/prerequisites.adoc
Fixes: #307 (Please note in docs: ARM 32 Bit is not supported)
Remove ARM32 support from prerequisites
=> Remove ARM32 support from prerequisites

antora.yml
Just adding a *comment* in the `antora.yml` file to remember that we use the doc branch and not master.
=> Add a comment in antora.yml

modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/deployment/configuration/_ocis-config.adoc, modules/ROOT/pages/deployment/container/container-setup.adoc, modules/ROOT/pages/prerequisites/prerequisites.adoc, modules/ROOT/pages/quickguide/quickguide.adoc
This fixes the path for the binary location of ocis from `/usr/bin/ocis` --> `/usr/local/bin/ocis` based on hint of @dragotin
=> fix_ocis_binary_location

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/generic-configs-tab-1.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/generic-configs-tab-2.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/generic-configs-tab-3.adoc
Fixes: #318 (Generic Config link broken)
The content was present, but the referencing adoc page files were missing - fixed.
=> Fix broken generic-config links

modules/ROOT/partials/deployment/services/env-and-yaml.adoc
As already prepared, this switches the output to the tabbed version as we have it in container orchestration. 
This is now possible based on a change in the UI css for tabs to avoid a right border line cut thru the table if  the table contents is bigger than the screen. The right borderline automatically adapts to the with of the embedded content + right margin.
=> For services: embedd tables and yaml in tabs

antora.yml, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Fixes: https://github.com/owncloud/ocis/issues/5200 ([FR] Move deployment examples to separate place to save bandwidth/storage)
* After the ocis repo got a docs stable branch we can reference to, some adoptions were needed.
* Adding methods how to download the composer examples more easily.
=> Using the correct doc branch in the ocis repo

antora.yml
This is a small fix to update the antora.yml file referencing the correct branch for master, which is technically the docs branch (in the ocis repo).
=> Fix antora.yml to reference the correct master version

modules/ROOT/examples/deployment/container/orchestration/values-overwrite-tab-1.yaml, modules/ROOT/examples/deployment/container/orchestration/values-overwrite-tab-2.yaml, modules/ROOT/examples/deployment/container/orchestration/values-overwrite-tab-3.yaml
The original comment was very long and therefore hard to read.
Making two lines from one.
=> Make some yaml comments multilined to improve readbility

modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/services.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc, modules/ROOT/partials/nav.adoc
Add the postprocessing service to the service list.
This also needed an adoption of the tab handling to only show tabs where the service is available.
Keeping this as draft until the service and variable descriptions are final.
@kobergj fyi
=> Add the postprocessing service

modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc, modules/ROOT/partials/nav.adoc
This PR adds a page covering environment variables with a special scope.
* Variables with extended scope do not directly configure services but functions underneath.
* Variables with a global scope can configure more than one service.
The page and the required stuff around in the documentation is ready, but the content coming from the ocis repo which gets included not. Extended scope vars are already available but the file needs renaming and the CI an update. The progarm that creates the table for global scope vars needs to be made.
Keeping this PR therefore as draft to avoid accidentially merging.
A language review for my comments is always welcomed.
@kobergj fyi
=> Special Scope Environment Variables

modules/ROOT/pages/deployment/general/general-info.adoc
Fixes: #288 (S3ng documentation)
Added a documentation about S3 bucket policy which is not only necessary for Helm but also in container deployments.
Needs PR [Complete description of STORAGE_USERS_DRIVER](https://github.com/owncloud/ocis/pull/5345) including the backport before merging to avoid referencing to content which is not fully present.
Therefore Set to draft to avoid accidentially merging.
=> Add a documentation about S3 bucket policy

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/ocdav.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/webdav.adoc
There were from history some paths to services hardcoded and not referenced via an attribute which was created for exactly that reason - fixed by using he attribute.
=> Consequently using the 's-path' attribute

modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc
Refernces: https://github.com/owncloud/ocis/pull/5378 ([docs-only] Backport Docs Helpers to 2.0)
This PR finalizes the colletcion of environment variables with special purpose.
Both `extended` and `global` ones are now shown in latest (master) and 2.0.0 (GA).
Tested via local build, currently visible for preview on staging.
=> Enable global envvars

modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc
Forgot to add an internal comment where to change extended envvar descriptions if one is empty. This PR does not change any content is is meant as reminder of one searches where to fix a missing entry.
=> Add internal comment to extended envvars

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Fixed a typo in the Helm documentation as dicsussed in RC.
It is not a switch (on-off) but one-time and off.
@d7oc FYI
=> Fix typo in the Helm documentation

modules/ROOT/pages/deployment/general/general-info.adoc
Add a description about S3 in the Default Paths section in the General Info documentation.
=> Add a description in the General/Default Paths section about S3

modules/ROOT/pages/deployment/wopi/wopi.adoc
=> Fix a typo

modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc
References:
https://github.com/owncloud/ocis/pull/5457 (Better Configuration for Postprocessing Service)
https://github.com/owncloud/ocis/pull/5467 ([docs-only] Fix Envvar Deprecation)
The postporcessing service got updated:
* new fuctionality
* the first deprecation
(note that this deprecation should be removed before the next stable release gets published)
Hurra, we have the first deprecation and it is working like a charm 😃 
Note that the text added is more or less a 1:1 copy of the text from the ocis repo, see 5457 above. If we find any changes (consider checking the whole document), we should do the changes in the ocis repo too.
Currently visible on staging
@kobergj fyi
=> Update the postprocessing service

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/maintenance/backup.adoc, modules/ROOT/pages/maintenance/restore.adoc
This PR updates:
* the description for paths used
* harmonizes the term **blob** and removes **user data**
* removes a statement in the restore documentation --> I have new info
to be added in a new document: migrate between ocis and s3 filesystems
=> Update of paths and terms used

modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Global- and Extended envvars do not have deprecations by design - needs to be handled differertly in the ocis code. No deprecations to be rendered - the file to include defining if there is a deprecation does not exist in that case and renders therefore to a 404.
=> Fix 404 for deprecations in extended and global envvars

modules/ROOT/pages/deployment/services/s-list/search.adoc
References:
https://github.com/owncloud/ocis/pull/5503 ([docs-only] search service readme).
#347 (Document how to add the full text search to ocis)
Adds a description based on the referenced PR (ocis repo) for the search service.
This does not fix #347 but is a requirement for addressing it.
Note that the text has already been reviewed in the ocis repo.
=> Add description for the search service

modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc
Referencing:
https://github.com/owncloud/ocis/issues/3917#issuecomment-1179507520 (Harmonize env variable naming for those which are not bound to a particular service)
There are two envvars that are not documented so far and cant be gathered automatically.
Those envvars are are only available when using the binary setup.
Any changes or additions for this type must be maintained manually.
The description text for the envvars is 1:1 from the ocis repo (origin).
@kobergj fyi, as discussed. Pls add a comment in the ocis config.go file as reminder that this needs manual maintenance and reference to the doc page on the web.
=> Add two Special Envvars

modules/ROOT/pages/conf-examples/office-integration.adoc
This adds a link to ONLYOFFICE where a hardware requirement description is documented.
=> Add hardware sizing to the Office documentation

modules/ROOT/pages/deployment/binary/binary-setup.adoc
The binary setup contained a legacy info that services can be started and stopped individually.
This is now corrected as there are other mechanisms to how to start and stop services.
@jnweiger fyi
=> Update binary setup

modules/ROOT/pages/deployment/services/s-list/webfinger.adoc, modules/ROOT/partials/nav.adoc
References: https://github.com/owncloud/ocis/pull/5373 (minimal webfinger)
The webfinger service has been added to the ocis repo, adding the service to the documentation.
The text originates from the readme of the webfinger service and has been slightly adapted for docs.
@butonic @micbar fyi
=> Adding the webfinger service

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Fixes: #379 (Wrong frontend.yaml filename)
Adds a note to yaml files in services because they need a proper naming.
On draft, waiting for dev feedback.
=> Add explanation text for yaml file naming

modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/partials/nav.adoc
References: https://github.com/owncloud/ocis/pull/5600 (Eventhistory Service)
This PR adds the eventhistory service which was recently added in the ocis repo.
@kobergj fyi
=> Adding the eventhistory service

modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc
The column widths of the table did not render well - fixed.
No text changes.
=> Correct column widths for the eventhistory service

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc
References: https://github.com/owncloud/ocis/pull/5615 ([docs-only] Add a basic storage-users readme only containing cli commands)
A new CLI command has been added to the `storage-users` service.
=> Add a new storage-users cli command

modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc
As the title says. Global envvars may not have a uniformed description in the servcies used.
=> Add a note that descriptions of global envvars can differ context based

modules/ROOT/pages/deployment/services/s-list/proxy.adoc
References: https://github.com/owncloud/ocis/pull/5617 (add config option to set default quota per role)
A new feature has been implemented, it can only be configured via yaml but not via envvar.
Note that in the referenced PR, additional quota functionality has been added not related to role based quota. It is just in one PR. Those envvars are added automatically by the doc process.
=> Add new quota per role feature description in the proxy service

modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/nav.adoc
References: https://github.com/owncloud/ocis/pull/5610 (Userlog Service)
As the title says.
Currently on draft, because the referenced PR is not merged.
More or less a copy of the eventhistory service + some changes.
=> Add the new userlog service

modules/ROOT/pages/deployment/services/s-list/auth-basic.adoc
Basic authentication should not be used in production (as already stated) but also not for benchmarking.
=> Update the basic-auth service

modules/ROOT/pages/deployment/services/s-list/graph.adoc
References: https://github.com/owncloud/ocis/pull/5694 (graph: Add support for "or" filter on /users)
Adding support to use `or` when filtering.
=> Update graph service

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/tls.adoc
When setting up ocis, accessing the webui or clients is defaulted to https wich can be changed by an environment variable. Though the description was already present, it is now added on a more prominent location including links to the details.
=> Describe that https is default to access the webui

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
References: https://github.com/owncloud/ocis-charts/pull/147 (- add support for Kubernetes sub versions)
As the title says.
Renders now as:
=> Add subversion explanation for Kubernetes versions

modules/ROOT/pages/deployment/services/ports-used.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/partials/nav.adoc
References: https://github.com/owncloud/ocis/pull/5716 (Introduce Policies-Service)
This PR adds the policies service to the documentation.
@fschade @kobergj @micbar fyi
=> Add the policies service

modules/ROOT/pages/deployment/services/ports-used.adoc, modules/ROOT/pages/deployment/services/s-list/app-provider.adoc, modules/ROOT/pages/deployment/services/s-list/app-registry.adoc, modules/ROOT/pages/deployment/services/s-list/auth-bearer.adoc, modules/ROOT/pages/deployment/services/s-list/auth-machine.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/groups.adoc, modules/ROOT/pages/deployment/services/s-list/idp.adoc, modules/ROOT/pages/deployment/services/s-list/notifications.adoc, modules/ROOT/pages/deployment/services/s-list/ocdav.adoc, modules/ROOT/pages/deployment/services/s-list/ocs.adoc, modules/ROOT/pages/deployment/services/s-list/search.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/deployment/services/s-list/sharing.adoc, modules/ROOT/pages/deployment/services/s-list/storage-publiclink.adoc, modules/ROOT/pages/deployment/services/s-list/storage-shares.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/store.adoc, modules/ROOT/pages/deployment/services/s-list/users.adoc, modules/ROOT/pages/deployment/services/s-list/web.adoc, modules/ROOT/partials/nav.adoc
Ports were described in some, but not all services.
This PR makes this consistent
Some minor fixes added.
=> Add missing port description to services

modules/ROOT/pages/deployment/services/s-list/proxy.adoc
References: #419 
Use the correct source macro for the examples.
=> Use correct source macro for proxy service

modules/ROOT/pages/deployment/container/container-setup.adoc
`exit` was shown as if it was available as key combination on the keyboard. But in fact it has to be typed so the layout should be as any other command.
=> Fixed typo

modules/ROOT/pages/deployment/services/s-list/invitations.adoc, modules/ROOT/partials/nav.adoc
Fixes #425 (Add Invitations Service)
Adds the invitations service.
Content has been copied from the referenced ocis repo PR where it was already reviewed by @EParzefall
=> Add the invitations service

antora.yml, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/ocs.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Fixes: #431 (The proxy service description needs an update because of caching)
Though I wanted to have that PR split into two, it accidentially happend to be one, my bad.
* There was a a tab mismatch introduced by
#434
Tabs in orchestration appeared where they shouldnt because the same attribute was used for both helm and services/compose. This is now fixed and tab appearance is based on different and independent attributes
* To make this more clear, I cleand up the `antora.yaml` file
I also prepared for ocis 3.0, but those tabs are not shown!
* Then I reviewed the envvar and yaml generating file. This is a first step but needs more work
* Finally, all services referenced via #431 are now updated accordingly
=> Fix tab mismatch and update services

modules/ROOT/partials/deployment/services/env-and-yaml.adoc
This PR makes that if one tab has a deprecation set, it shows the deprecations for all tabs.
Preferrably we would like to show deprecations tab dependent where set, but antora does not evaluate attributes set inside the tab definition, - which is here the case by including files. Attributes must be defined outside the tab. There is also no secure possibility to add an attribute in the source (oics-repo) because we would need to add an additional attribute dependent on the branch where the source is located.
Therefore this is, post intense evaluation and for the time being, the best method.
When antora changes the behaviour, we can re-evaluate.
=> Fix attributes calculation in env-and-yaml.adoc

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
With https://github.com/owncloud/ocis-charts/pull/181 we also bump the version the oCIS chart will use by default. Thus the documentation has to be adjusted as well.
=> Update supported oCIS versions for helm charts

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/depl-examples/small-scale.adoc, modules/ROOT/partials/nav.adoc
Calling this installation method "small" puts out a wrong impression. Thus more the focus on bare metal installation.
=> Replace small with bare metal

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/maintenance/b-r/backup.adoc, modules/ROOT/pages/maintenance/b-r/restore.adoc, modules/ROOT/pages/prerequisites/prerequisites.adoc, modules/ROOT/pages/prerequisites/xattrs.adoc
Fixes #415 (Add messagepack metadata backend)
This PR moves from the xattr to the messagepack backend.
The xattr description has been moved to its own page (with noindex) and got an Important note + link in prerequisites. This allows an easy removal of content when we have a post 3.0 release.
All locations where xattr were present are fixed.
=> New metadata backend

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/deployment/services/s-list/idm.adoc
Fixes: #445 (More precision of the IDM limits)
References: https://github.com/owncloud/ocis/issues/5961 (2-Factor Authentication 2FA)
* The limitations of the IDM service compared to an LDAP server needs more details like that no 2FA or device management is possible.
* Added a link in the bare metal deployment document to the IDM service
=> Update the IDM limitations with regards to an LDAP server

modules/ROOT/pages/deployment/services/s-list/proxy.adoc
Fixes: #451 (proxy service: oidc role mapper to allow multiple matching roles)
Apply the changes from the ocis-repo proxy readme, see referenced issue.
Needs the referenced PR to be merged first, setting to draft therefore.
=> Update the proxy service for multiple matching roles

modules/ROOT/pages/deployment/services/s-list/notifications.adoc
Fixes: #259 (Document eMail templating in ocis)
Adds a description about email templating in the notification service.
=> Add notification email template description

modules/ROOT/pages/deployment/binary/binary-setup.adoc, site.yml
adjust the output of the version command to the reality
=> fix version output

modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/ocs.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc
References: https://github.com/owncloud/ocis/pull/6119 ([docs-only] Add caching/storing info to services where missing)
**DO NOT MERGE** before the referenced PR got merged !
Adds/corrects missing info in README.md for services with respect to caching/storing.
=> Add caching/storing info to services where missing

modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
References: #468 (Add caching/storing info to services where missing)
Missed to make tables instead of text in two services.
=> Fix tables for caching in two services

modules/ROOT/examples/deployment/container/orchestration/nginx-ingress-tab-1.yaml, modules/ROOT/examples/deployment/container/orchestration/nginx-ingress-tab-2.yaml, modules/ROOT/examples/deployment/container/orchestration/nginx-ingress-tab-3.yaml
changed host name in the NGINX Ingress Example: 
- https://doc.owncloud.com/ocis/next/deployment/container/orchestration/orchestration.html#kubernetes
=> Changed host in the container orchestration section

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
merge only after https://github.com/owncloud/ocis-charts/pull/211
=> update supported ocis version for latest helm chart

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Fixes: #465 (Document Config Override Files (yaml))
Add a note when using config overrides
=> Note for Helm chart config overrides

modules/ROOT/pages/deployment/container/container-setup.adoc
Fixes: #476 (Docker Desktop is available for ubuntu > 21.10 or 22.04)
Docker Desktop got an update
=> Update of the GUI for Docker section

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc
References: https://github.com/owncloud/ocis/pull/6193 ([docs-only] Update the PROXY_TLS envvar description)
`PROXY_TLS` needs clarification to avoid setup issues.
=> Update the proxy service and general info (PROXY_TLS)

modules/ROOT/pages/deployment/webui/webui-customisation.adoc, modules/ROOT/pages/deployment/webui/webui-theming.adoc, modules/ROOT/pages/deployment/webui/webui.adoc, modules/ROOT/partials/nav.adoc
References: https://github.com/owncloud/ocis/pull/6188 (Hardcoded web options)
Adding the WebUI / Customisation and Theming documentation.
Note that the theming content was originally in the webui user docs. With this PR we have it copied to the admin docs. As nextstep I need to remove it from the user docs and do a page alias to the old name/location.
=> Add WebUI to the admin documentation

modules/ROOT/pages/deployment/webui/webui-theming.adoc
References: #486 (Add WebUI to the admin documentation)
Adding a page alias after the relocated page got removed from the source repo.
Locally tested, alias works.
=> Add page alias to relink to old theming page in the webui repo

modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
References: https://github.com/owncloud/ocis/pull/6224 ([docs-only] Add readme.md note to not use xattrs anymore)
* Adding a note that xattrs should not be used anymore
* Fixed that the storage-system service is missing the caching description
=> Add a note to not use xattrs anymore

modules/ROOT/pages/deployment/services/s-list/web.adoc, modules/ROOT/pages/deployment/webui/webui-customisation.adoc
References: https://github.com/owncloud/ocis/pull/6229 ([docs-only] Deprecate some web envvars)
This completes the WebUI documentation (for the time being) based on changes in the referenced ocis PR.
Only merge when the referenced PR got merged.
=> Add more WebUI config descriptions

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
only to be merged after https://github.com/owncloud/ocis-charts/pull/250
=> update supported oCIS version for Helm Chart

modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/ocs.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/multi-location/caching-list.adoc
This PR fixes the following:
* Make the main part of the caching and persistence table a partial.
This eliminates rewriting stuff again and again which is error prone and eases changes
* Fix wrongly used envvars in caching descriptions (graph and proxy)
* Remove caching from the ocs service as it is no longer present
Needs a PR in the ocis repo too for fix and remove things.
=> Fix Caching Setup

modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/partials/multi-location/caching-list.adoc
References: https://github.com/owncloud/ocis/pull/6274 ([docs-only] Create README for settings service)
Adding the following to the settings service description:
* Content what the service is about
* Caching
Plus a small cleanup in the caching partial.
=> Add content and caching to settings

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
Fixes: #505 (storage-users service got cache envvar added)
This PR adds the new `STORAGE_USERS_ID_CACHE_STORE` envvar to the caching description.
=> Add new caching envvar to storage-users service

modules/ROOT/pages/index.adoc
This adds a pdf version of a slide deck describing infinite Scale created by @tbsbdr at the most prominent location - the introduction section of the ocis main page.
I have slightly adapted to pages:
* Page 1:
Only showing `May 2023` instead of `May 2023 (current)`
* Page 13:
Aligning image and text
=> Add ocis overview presentation to introduction

modules/ROOT/pages/maintenance/commands/commands.adoc
Fixes: #413 (New ocis commands for metadata)
Add a new metadata manipulating CLI command to the list of commands.
Note that the printout is at is is and comes from running the command.
=> Document metadata CLI command

modules/ROOT/pages/index.adoc
The removed note was double present. First appearance is on top in section "Brief Overview".
=> Remove double present note

modules/ROOT/pages/deployment/services/s-list/search.adoc
Fixes: #514 (New setting: Do not try to fulltext-index large files (search service))
Add envvar limiting content extraction file size.
=> Update search service content extraction file size limit

antora.yml, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
to be merged after https://github.com/owncloud/ocis-charts/pull/303 and when 0.3.0 tag is created on the helm chart repo
=> prepare ocis chart 0.3.0 release with ocis 3.0.0

antora.yml, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/breaking-changes.adoc
References: #521 (Add Helm Chart Breaking changes (if any) )
THIS IS PART ONE OF (at least) TWO or more and fixes the following:
* Set the correct HC version (0.1.0 instead of 0.2.0, falsly changed in #519 by me)
* Add a description why 0.2.0 is in breaking changes but not available as supported release
* Add a Breaking Change section for 0.3.0
* Add some content for 0.3.0 <-- This is not finished but the rest of the PR needs merging
To finish Helm Charts, we need to wait until all available breaking changes are known which is WIP atm, see the referenced issue.
@wkloucek @micbar fyi
=> Fixes Helm Charts Part ONE

modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/migration/upgrading-ocis.adoc
Referencing: https://github.com/owncloud/ocis/pull/6475 (OIDC authentication using authelia fails with no roles)
The referenced issue highlighted that `Automatic Role Assignments` need a review when upgrading to 3.0
* Add `Automatic Role Assignments` to the upgrade list
* Open linked documents in new tabs
* Improve readbility in the referenced proxy document
Note that no change is necessary in the doc release notes as we already point to this migration guide.
@micbar @rhafer fyi
=> Migration: add Automatic Role Assignments to the list

modules/ROOT/pages/migration/upgrading-ocis.adoc
Referencing: https://github.com/owncloud/ocis/issues/6505 (LDAP Documentation Feedback and Implementation Suggestion)
A new upgrading step is necessary.
@tbsbdr this step is important as it deals with a bug recently found that imho needs mentioning in the release notes (known issues).
=> Add a new upgrading step

modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc
Fixes: #534 (ResumePostprocessing Event (CLI) )
Adding a new CLI command that allows to resume an errored postprocessing step.
=> CLI Resume Postprocessing

modules/ROOT/pages/conf-examples/search/configure-search.adoc
It was a relative link instead of an absolute one before:
=> Fix Tika Server link in search docs

modules/ROOT/pages/deployment/services/s-list/antivirus.adoc
According to https://github.com/owncloud/ocis/issues/6494#issuecomment-1598524794
`ANTIVIRUS_INFECTED_FILE_HANDLING = "continue"` option should only be used for debugging purposes. So this PR updates the wording to make it clear.
There are also other grammatical fixes done
=> Update the antivirus docs to mention that continue is for debug purposes only

modules/ROOT/pages/deployment/services/s-list/app-provider.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/idm.adoc, modules/ROOT/pages/deployment/services/s-list/invitations.adoc, modules/ROOT/pages/deployment/services/s-list/nats.adoc, modules/ROOT/pages/deployment/services/s-list/ocdav.adoc, modules/ROOT/pages/deployment/services/s-list/web.adoc, modules/ROOT/pages/deployment/services/s-list/webdav.adoc, modules/ROOT/pages/deployment/services/services.adoc
References: #546 (Add table with service per release)
* Some service texts have been corrected in the summary page (see referenced PR) but not in the service pages. This is now in sync again, taking the corrections of course 😄
* The first table column in listing the services needed to be extended a bit to avoid line breaks
=> Some service text cleanups

modules/ROOT/pages/maintenance/commands/commands.adoc
Fixes: #545 (New CLI: ocis decomposedfs check-treesize)
Add the new CLI: `ocis decomposedfs check-treesize`
=> Add CLI ocis decomposedfs check-treesize

modules/ROOT/pages/deployment/services/s-list/userlog.adoc
Fixes: #553 (Add SSE in the userlog service)
Add a description to the userlog service for Server-Sent Events (SSE).
=> Add Server-Sent Events to userlog service

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/migration/upgrading-ocis.adoc
References: https://github.com/owncloud/ocis/issues/6722 (Infinite loop when trying to login)
* Adding an explicit warning that messagepack migration is one way. Note that we have a statement on top of the document stating that upgrades are always forward only, adding this makes this more prominent for this case. Backwards only with a full restore.
* ~Added an explicit warning that third party Helm Charts are outside of any ownCloud support or responisibility.~
--> adapted the section headline instead
=> Adding warnings for messagepack migration and third party Helm Charts

modules/ROOT/pages/prerequisites/prerequisites.adoc
The info deleted is outdated and was missed to be removed when updating to messagepack.
@individual-it FYI
=> Remove outdated xattrs note

modules/ROOT/pages/additional-information/knowledge-base.adoc
Fixes: https://github.com/owncloud/ocis/issues/5466 CORS policy while getting token information from Keycloak
This adds info that CORS also needs to be configured in Keycloak.
@micbar FYI
=> Add CORS to Knowledgebase

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
References: https://github.com/owncloud/ocis/pull/6840 (storage-users: Add config option for graceful shutdown timeout)
* Add the text from the referenced readme (already reviewed by edith),
* Add a link the bare metal deployment.
=> Graceful Shutdown storage-users service

modules/ROOT/pages/additional-information/kb-documents/fail2ban-protect-login.adoc
This is a mini fix in the fail2ban documentation to fix a link.
`xref` was accidentially assigned and is now removed to make the link working.
=> Mini fix to repair a link

modules/ROOT/pages/deployment/binary/binary-setup.adoc
Fixes: #570 (Change the command for running the ocis in detached mode in case of ZSH shell for binary setup)
`disown` in zsh takes `job id` not the `process id` and `$!` gives `process id` so it does not work.
The system also logouts if the shell is terminated.
`%%` gives the `current job id` so this is used instead of `$!`
=> Fix ZSH shell command

modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/pages/maintenance/commands/node-metadata.adoc, modules/ROOT/pages/maintenance/commands/node-tree-size.adoc, modules/ROOT/pages/maintenance/commands/rolling-back-and-forward.adoc
Fixes #574 (New ocis decomposedfs command)
* Add the new CLI command with an own page for the details
* Create for similar commands an own page that get linked, makes it easer to read
Note though I tried to make the pages themselves invisible to the content catalog (no clickable url) which could be done using an underscore in front of the filename, those files can only be included correctly but not xref'ed. We need xref to point to them...
=> CLI command to roll back and roll forward decomposedFS migrations

modules/ROOT/pages/deployment/services/s-list/policies.adoc
Fixes: #580 (Add mime to policies)
Adds the description for manually configured mime types to the policies service.
~Currently on draft to avoid accidentially merging until the referenced ocis PR gets merged.~ Merged
=> Add manually configured mime.types to the policies service

modules/ROOT/pages/deployment/services/s-list/policies.adoc
References: #581 and https://github.com/owncloud/ocis/pull/6965 (fix: fix readme and changelog env var)
Accidentially using the wrong envvar - corrected.
=> Fix using the wrong envvar in policies

modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/pages/maintenance/commands/rebuild-jsoncs3-indexes.adoc, modules/ROOT/pages/migration/upgrading_3.0.0_3.1.0.adoc
Fixes: #585 (New command: ocis migrate rebuild-jsoncs3-indexes)
* Add a new `ocis migrate command` to the maintenance commands documentation
* Add that command also to the upgrade documentation
Locally rendering is fine.
@aduffeck fyi as discussed
=> Add Repair and Migrate jsoncs3 Indexes command

modules/ROOT/pages/deployment/services/s-list/userlog.adoc
Fixes: #578 (Update userlog description)
The userlog description needs an update according the refrenced issue/PR.
Setting to draft to avoid accidentially merging until the ocis PR gets merged.
=> Update userlog description

modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/pages/migration/upgrading-ocis.adoc, modules/ROOT/pages/migration/upgrading_3.0.0_4.0.0.adoc
This renames the ocis release from 3.1 to 4.0.0 as discussed with @micbar 
(Additional migration steps to the already written will follow in a separate PR)
=> Make the version 4.0.0 instead of 3.1

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/migration/upgrading-ocis.adoc, modules/ROOT/pages/migration/upgrading_3.0.0_4.0.0.adoc
This is an addon to the migration guide for 4.0 for the breaking change.
You can see the rendered changes on staging in the migration section in:
`ocis/next/migration/upgrading-ocis.html` and the subsequent page.
The removal of the text block in `orchestration.adoc` was necessary as already described above.
@phil-davis language review welcomed.
@tbsbdr FYI
=> Add migration and Breaking Changes

README.md, docs/new-infinite-scale-release-info.md
We were lacking an info about the background and tasks to do when a new ocis release gets released.
=> Add a task info section when there is a new ocis release

antora.yml, modules/ROOT/pages/conf-examples/office/office-integration.adoc, modules/ROOT/pages/deployment/services/s-list/antivirus.adoc, modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/invitations.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc, site.yml
References: #576 (ocis 3.1 upgrade) and #593 (Make the version 4.0.0 instead of 3.1)
These are the changes necessary to render 4.0 properly.
With the referenced PR, the upgrade procedure has been merged already.
Note that though `docs-stable-4.0` is already set in `antora.yml`, it does currently not exist in the ocis repo. When testing, you will therefore get not all content rendered properly.
**Merge only** after testing when the necessary ocis doc branch has been created.
**Important**, the [Helm Chart part](https://github.com/owncloud/docs-ocis/issues/538) is NOT covered here and must be done in a separate PR.
@micbar fyi
=> Changes for 4.0 to render content properly

modules/ROOT/pages/maintenance/commands/rebuild-jsoncs3-indexes.adoc, modules/ROOT/pages/migration/upgrading_3.0.0_4.0.0.adoc
Based on a user feedback, we needed to sharpen the `ocis migrate rebuild-jsoncs3-indexes` command.
In addition, the upgrade guide needed an update which services need to be started mandatory.
=> Updating the ocis migrate rebuild-jsoncs3-indexes command

modules/ROOT/pages/deployment/services/s-list/antivirus.adoc
As outlined (and tested by myself) `ANTIVIRUS_CLAMAV_SOCKET` can take local and remote sockets, see also https://owncloud.dev/ocis/development/testing/#running-test-suite-with-antivirus-service-antivirus.
This PR adapts the documentation to reflect this.
=> Adapted socket description to software

antora.yml, site.yml
There is  a ocis patch release 4.0.1
Adapting site.yml and antora.yml so that all gets renderd properly.
No content change.
Note that there will be a docs change too with adding release notes.
=> Render the ocis 4.0.1 version in tabs

modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/idm.adoc
We have a envvar that can define the behaviour restricting username patterns. Though this envvvar is described in the envvar docs, it did not contain all relevant info about the current behaviour making it hard to understand what it is about and its impact. In addition, the envvar is not in IDM but in graph making it even more complicated to find. This PR fixes this issue.
A language review is welcomed.
=> Add "Restrict Username Patterns"

antora.yml, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/_kube-versions-tab-1.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/_kube-versions-tab-2.adoc, modules/ROOT/pages/deployment/container/orchestration/tab-pages/_kube-versions-tab-3.adoc
References: https://github.com/owncloud/ocis-charts/pull/392 (drop Kubernetes version enforcment and test Kubernetes 1.18)
If the referenced PR gets merged, there are no more "automatic" updates of the supported kubernetes versions coming from ocis-charts.
To make that situation future proof, I migrated all the version tables into this repo eleminating the dependency. If there are any changes necessary, they can now be done here. There is also a small description text as comment what to do in which case.
Note that in ocis-chart issue: https://github.com/owncloud/ocis-charts/issues/338, an additional column is shown: `api compatible` - this can be added on demand quite easily, also as later step.
The new layout can be seen online on staging: …
=> Make the source of Kubernetes versions supported part of this repo

modules/ROOT/pages/deployment/services/s-list/policies.adoc
References: https://github.com/owncloud/ocis/pull/7311 ([docs-only] Add denied error body to docs)
Adding the referenced info to the admin docs.
=> Add denied info response to policies service

antora.yml, site.yml
We have released ocis 4.0.2 recently.
This PR prepares docs-ocis for this release.
(updating the releases for server too, but these are only relevant for local building...)
=> Prepare for ocis 4.0.2

modules/ROOT/partials/deployment/nginx_harden_ssl.adoc
Supercedes: #626 (Update nginx_harden_ssl.adoc)
Adding a note to avoid a nginx config error when certbot has its own defined ciphers.
=> Add info when defining ciphers for Nginx with Letsencrypt

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/deployment/general/general-info.adoc
Fixes: #623 (Avoid a very common pitfall with PROXY_HTTP_ADDR)
This clarifies and improves the decription for the `PROXY_HTTP_ADDR` envvar.
=> Clarify the PROXY_HTTP_ADDR description

modules/ROOT/pages/deployment/services/ports-used.adoc, modules/ROOT/pages/deployment/services/s-list/clientlog.adoc, modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/store.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/deployment/services/log-service-ecosystem.adoc, modules/ROOT/partials/nav.adoc
Fixes: #612 (New service: Clientlog)
Add the `Clientlog` service.
Note that we already have a reference to the upcoming SSE service which will be added with the next PR.
=> Add Clientlog service

modules/ROOT/pages/deployment/services/s-list/frontend.adoc
Fixes: #609 (PWD policy (frontend service) for public link password validation)
The password policy description for public link password validation is now added to the frontend service.
Note that the text used was already reviewed in ocis, though improvements can always be found.
=> Add the password policy to the frontend service

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Change incorrect option name hostAlias to hostAliases
```yaml
hostAliases:
- ip: "192.168.49.2" # <- needs to be the IP of `minikube ip`
hostnames:
- "ocis.kube.owncloud.test"
```
=> fix for mac configuration

antora.yml, modules/ROOT/examples/deployment/container/orchestration/userlog-global-notifications-secret-tab-1.yaml, modules/ROOT/examples/deployment/container/orchestration/userlog-global-notifications-secret-tab-2.yaml, modules/ROOT/examples/deployment/container/orchestration/userlog-global-notifications-secret-tab-3.yaml, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc
- userlog global notifications secret
=> Helmchart notification secrets

modules/ROOT/pages/deployment/services/s-list/notifications.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc
Fixes: #630 (Update settings service description)
Adds the default language description in the settings service (+ userlog and notifications)
Set to Draft as the referenced ocis PR is not yes merged.
=> Default language

modules/ROOT/pages/deployment/services/_special-envvar.adoc, modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/pages/deployment/services/envvar-types-description.adoc, modules/ROOT/pages/deployment/services/s-list/antivirus.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Fixes: #648 (Add to each service a description how values of envvars are notated/treated)
This is the first step in fixing the issue that we have no documentation for how envvar types are treated and which values are allowed in which format.
The document is referenced on each service envvar description automatically on top of the table.
As next step, we need to fix _all_ the texts and defaults for envvars with arrays as the examples are written with blank instead of comma.
The current built can bee seen on [staging](https://doc.staging.owncloud.com/ocis/next/deployment/services/s-list/antivirus.html#configuration).
Note when merged, we can reference the document in the dev docs as that is quite complicated to rebuild in markdown and doubles work for maintenance.
Note that the docuement is …
=> Add envvar type description

modules/ROOT/pages/deployment/services/s-list/idp.adoc
Fixes: #650 (No theming / not being brandable to be listed as a limitation of the builtin IDP)
Adding a text to describe limitations of the internal IDP service.
=> Add a limitations description to the IDP service

modules/ROOT/pages/deployment/services/s-list/audit.adoc
Fixes: #646 (Improve the audit service description)
The description of the audit service needs to be more precise.
Note while working on it, we need to update some envvar descriptions too.
=> Improve the description of the audit service

modules/ROOT/pages/deployment/services/s-list/frontend.adoc
Fixes: #676 Use global variables for password policy in the frontend service
Change some envvars from local to global to be inline with ocis dev docs, see referenced issue.
=> Use global variables for password policy in the frontend service

antora.yml, site.yml
Small updates to `site.yml` (for local build only) and `antora.yml`.
Note that the vesion changes may be updated soon again.
Note that the link change in site.yml is only for completeness
=> Update site.yml and antora.yml

modules/ROOT/pages/deployment/container/container-setup.adoc
Part of: https://github.com/owncloud/ocis/issues/7940
While testing the docs for the docker container following command responds
```console
docker run --rm -it \
--mount type=bind,source=$PWD/ocis/ocis-config,target=/etc/ocis \
owncloud/ocis init
```
```console
Do you want to configure Infinite Scale with certificate checking disabled?
This is not recommended for public instances! [yes | no = default] 
=========================================
generated OCIS Config
=========================================
configpath : /etc/ocis/ocis.yaml
user       : admin
password   : <some-value>
```
The config path is ` /etc/ocis/ocis.yaml` and not `/etc/ocis/ocis-config/ocis.yaml` . I don't know if this is an expected path or not but the command responds as such and the setup also works. 
This PR …
=> docs: fix the ocis init config path in the docs

modules/ROOT/pages/deployment/binary/binary-setup.adoc
There is an error while this command is run according to docs of sytemd service:
`sudo journalctl -f -u ocis`
In this PR, changes have been made to address the issue by adding some env variables
- Fixes https://github.com/owncloud/docs-ocis/issues/692
=> docs: fix systemd setup with single binary docs

modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/services/s-list/search.adoc, modules/ROOT/pages/deployment/services/services.adoc
These xrefs have been identified to cause errors and needed a fix.
=> Fix faulty xrefs found during the antora upgrade

antora.yml, modules/ROOT/pages/conf-examples/office/ext-files/app-registry.adoc, modules/ROOT/pages/conf-examples/office/ext-files/docker-compose.adoc, modules/ROOT/pages/conf-examples/office/ext-files/env.adoc, modules/ROOT/pages/conf-examples/office/ext-files/wopiserver.adoc, modules/ROOT/pages/conf-examples/office/office-integration.adoc, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Fixes: #675 ([5.0] Versionize the ocis admin docs)
This PR:
* Removes ALL versioned stuff from the master branch shown as `next` in the URL.
* In existing tabs, keeps only one tab with a heading to show where we are where applicapable.
* Only uses the necessary data for the tab heading and it's content sourced from `antora.yml`.
* Prepares to branch off a version where the tab related stuff needs some changes in the upcoming release branch
* When branching has finished, we need to do a small cleanup task to remove all commented out attributes not longer necessary. Currently we keep them to make preperation easier.
**NOTE:** Versioning ocis has finished when the branches needed are created, which are 4.0 and 5.0 !!
**NOTE:** For the upcoming branching tasks, the branches will get the …
=> Make the ocis content versioned

.drone.star
This PR corrects the `latest_version` in `.drone.star` for the 4.0 branch.
Missed when creating the 4.0 branch.
=> Correct the version in .drone.star in 4.0

.drone.star
Fixes the `base_branch` for the upcoming pdf build in .drone.star, just for completeness.
=> Minor fix for completeness in .drone.star in 4.0

antora.yml, site.yml
The sources referenced were still on 4.0.
Now they are on 5.0
=> Make the 5.0 release point to the correct ocis branches.

modules/ROOT/pages/deployment/services/env-var-changes.adoc, modules/ROOT/partials/deployment/services/general-info/env-var-changes/added-4.0.5-5.0.0.adoc, modules/ROOT/partials/nav.adoc
References:
https://github.com/owncloud/ocis/pull/8353 ([docs-only] Add new variable delta list between 4.0.5 and 5.0.0-rc1)
https://github.com/owncloud/ocis/pull/8377 ([docs-only] Add .adoc table version to env-var-deltas)
This are the first changes adding a delta envvar list. **IT IS NOT COMPLETE NOR FINAL**
But to add the structure and make it referencable, we are starting with that.
Review note: do not edit the table itself, it is sourced from the ocis repo (just copied atm, but included later)
Note that following changes will take place with later PR's:
* Make the tables an include from ocis.
By that removing the partials
* Adding a "removed" table
=> Added a page with changed envvars based on the version

modules/ROOT/pages/deployment/services/env-var-note.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Fixes: #708 ([5.0] Use env variable in yaml config files)
Adding envvars to yaml configs:
* Creating a general description text.
* Adding a note in the partial that will then show up automatically in any service where defined.
=> Add envvars to yaml config

modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/multi-location/caching-list.adoc
Fixes: #721 ([5.0] Use global envvar for cache or store description)
This PR makes the use of local and global envvars in caching more clear.
=> Make local/global envvars in caching more clear

modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/deployment/general/general-info.adoc
Fixes: 714 ([5.0] change ocis basepath from home to /etc)
Add an info to use `$HOME` and `~` for config and data dir.
=> Update the General Info page with $HOME and ~ for config and data dir

modules/ROOT/pages/deployment/services/caching.adoc, modules/ROOT/pages/deployment/services/s-list/antivirus.adoc, modules/ROOT/pages/deployment/services/s-list/audit.adoc, modules/ROOT/pages/deployment/services/s-list/clientlog.adoc, modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/notifications.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/search.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/deployment/services/s-list/sharing.adoc, modules/ROOT/pages/deployment/services/s-list/sse.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/multi-location/caching-list.adoc, modules/ROOT/partials/multi-location/event-bus.adoc
Fixes: #684 ([5.0] Cache Store changes in several services)
First commit fixing classical caches and persistances.
I need fo make another commit adding changes for the event bus, occurences in the ocis repo/services see below:
`find . -path '**/pkg/config' -exec grep -rn OCIS_EVENTS_AUTH_USERNAME {} \; | sort`
```
./antivirus/pkg/config/config.go:57:	AuthUsername         string `yaml:"username" env:"OCIS_EVENTS_AUTH_USERNAME;ANTIVIRUS_EVENTS_AUTH_USERNAME" desc:"The username to authenticate with the events broker. The events broker is the ocis service which receives and delivers events between the services."`
./audit/pkg/config/config.go:32:	AuthUsername         string `yaml:"username" env:"OCIS_EVENTS_AUTH_USERNAME;AUDIT_EVENTS_AUTH_USERNAME" desc:"The username to authenticate with the …
```
=> Update caching and persistence

modules/ROOT/pages/deployment/services/s-list/ocs.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/store.adoc
Fixes: #720 ([5.0] Make store service configurable)
* Adding description text to the proxy and ocs service
* Add a deprecation note to the store service
NOTE: the new envvars need to be added in the ocis repo in to the 4-5-added file immediately.
Done with: https://github.com/owncloud/ocis/pull/8556
=> Make store service configurable

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/maintenance/space-ids/space-ids.adoc, modules/ROOT/partials/multi-location/caching-list.adoc, modules/ROOT/partials/nav.adoc
Fixes: #679 ([5.0] AND [4.0] New / deprecated ocis cli commands)
This PR:
* adds new commands as listed in #679 
* adds a page describing how to get a spaceID that is a required parameter in `trash-bin` commands
Currently visible on [staging](https://doc.staging.owncloud.com).
Backport to 5.0, partially to 4.0
Important: the content that is in the storage-users readme in the ocis repo needs a rewrite according the changes made in the service description here.
@2403905 many thanks for your support and clarifications!
=> Updating the storage-users service description

modules/ROOT/pages/migration/upgrading-ocis.adoc, modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc
The migration guide needed an update because of changes in resharing.
=> Migration guide update because of resharing changes

modules/ROOT/pages/deployment/general/general-info.adoc
Fixes #714 ([5.0] change ocis basepath from home to /etc)
The base data bath (and config path) description needed an update due to changes in ocis:
* No `~` sign as replacement for `$HOME`
* Text fixes
* Rendering improvements for ease of readability
* List update for envvars that can overwrite the default base path
* Updated `ocis list` output
Currently visible on staging
=> Fix ocis base data path for binary

modules/ROOT/pages/deployment/binary/binary-setup.adoc
Just another location I missed before to fix `~` --> `$HOME`.
Also fixed a broken link.
=> Fixing another $HOME usage

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/deployment/binary/binary-setup.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/logging.adoc, modules/ROOT/partials/multi-location/idm-https-reverse-proxy.adoc
While reviewing another topic, I identified that the binary installation and related documents needed an urgent update.
Currently visible on staging
=> Update binary installation and related documents

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc
Fixes: #765 ([5.0] Use env variable in yaml config files)
The description how to use envvars and yaml got an update.
It is now more clear to read and contains the referenced change.
=> Update envvar and yaml use description

modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
Fixes: #771 (The storage-users uploads sessions command was updated)
* Adding cross references for the issue between postprocessing and storage-users.
* Updating the command according the referenced issue. 
Backport to 5.0 (part of the 5.0.1 release)
Some changes need transfer back into the ocis service readme.
=> Update of the restart postprocessing process

antora.yml
Make some comments in `antora.yml` more precise.
No backport, already added in 5.0 branch via #781
=> Fixing comments in antora.yml

modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc, site.yml
This PR creates a fix to always print in the upgrade guide a numbered version for docker pull and never master. It also takes care that we reference the target version we upgrade to and nothing else.
This avoids printing master for next. It is also future proof when we have a new version and copy and adapt the content, as we use attributes for the version.
The changes in site.yml are only relevant for local building and consistency.
=> Fix for docker pull in upgrade to print the correct version

modules/ROOT/pages/deployment/services/s-list/proxy.adoc
Fixes: #664 ([5.0] Add documentation for proxy routes)
Just a small text addon for the proxy service docs.
=> Small change to the proxy service documentation

modules/ROOT/pages/deployment/services/s-list/frontend.adoc
Fixes: #685 ([5.0] New envvar to disable password policy)
Add list item in the frontend service documentation to allow disabling the passsord policy.
=> Describe allow disabling the password policy

modules/ROOT/pages/deployment/storage/general-considerations.adoc
Just a small fix to improve the table for NFS in the general storage section.
NFS now shows similar to S3 the envvar where you can define the location for blobs.
=> Fixing the NFS storage table

antora.yml
Make ocis 5.0.2 the new latest in 5.0
No porting, only in 5.0
=> ocis 5.0.2 patch release

site.yml
Relevant only for local building docs.
=> Update site.yml for local building only

modules/ROOT/pages/deployment/general/general-info.adoc
=> Fix typo in general-info.adoc

modules/ROOT/pages/deployment/binary/binary-setup.adoc
The ps command was missing a minus symbol, correct is `-ax`.
Additionally, I made all components multilined.
Backport to 5.0 necessary.
=> Fix ps command in binary description

modules/ROOT/pages/deployment/binary/binary-setup.adoc
Not 100% sure. please double check.
I believe mDNS is not a prerequisite. I non't have it in any of my test sysstems, and I see no mentioning elsewhere in the docs.
=> Fix: Remove mDNS from binary-setup.adoc ?

modules/ROOT/pages/deployment/services/ports-used.adoc, modules/ROOT/pages/deployment/services/s-list/collaboration.adoc, modules/ROOT/partials/nav.adoc
Referencing: https://github.com/owncloud/ocis/pull/8374 (feat: add new collaboration service (WOPI))
Adds the new collaboration service to the documentation.
This PR also removes the build errors because of missing references to the collaboration service.
Note, some text changes need to be transported to the ocis repo.
NO backport!
=> Add the collaboration service

antora.yml, site.yml
Referencing: https://github.com/owncloud/docs-main/pull/39 (Release notes for ocis 5.0.3)
Making Infinite Scale pointing to the 5.0.3 version
NO porting!
=> Referencing Infinite Scale 5.0.3

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/general/ocis-init.adoc, modules/ROOT/pages/deployment/index.adoc, modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/partials/multi-location/event-bus.adoc, modules/ROOT/partials/multi-location/idm-https-reverse-proxy.adoc, modules/ROOT/partials/nav.adoc
Supersedes: #804 (Fix: paths for default deployments, Update general-info.adoc)
The bare metal deployments got revised and restructured.
Currently visible on [staging](https://doc.staging.owncloud.com/ocis/next/)
=> Fix the Bare Metal deployments

site.yml
This is a small `site.yml` update **only relevant for master**.
Makes rendering for local builds showing the correct download version - eases testing.
=> Small site.yml update for master only

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
References: https://github.com/owncloud/ocis/pull/9041 ([full-ci] Assimilate clean command into sessions)
The sessions command has been updated.
No backport!
=> Update storage-users uploads sessions command

modules/ROOT/pages/deployment/general/general-info.adoc
This is just a small fix to render a block containing callouts correctly.
Before it was rendered as source block, now it is renderd as plain verbatim block. The differernce is, that when using source as parameter, highlight js gets triggered and with it its css rules making the background black as we have with command examples. As this is not a command example but a listing, this was looking bad.
The change is necessary because of the recent docs-ui change fixing hljs rendering.
=> Render fix in the general-info page

modules/ROOT/pages/deployment/general/general-info.adoc
When working on the easy install docs, I identified that for resetting the admin pwd, the compose env must be downed. Stopping or pausing is not sufficient.
=> Clarify text for reset admin passwd

antora.yml, site.yml
References: https://github.com/owncloud/docs-main/pull/42 (Add release notes for ocis 5.0.4)
No backport, 5.0 only !
=> Make ocis 5.0.4 the actual version

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/monitoring/prometheus.adoc
We missed a text to descibe that we can define which services get started by the supervisor. The envvars relevant for this were already present but you needed to find them.
=> Add text how to manually define which services will be started

site.yml
This is just a small fix and only valid for local builds, but I need that for the easy entry docs.
NO backport !
=> Fix site.yml for local rendering only

modules/ROOT/pages/monitoring/prometheus.adoc
References: https://github.com/owncloud/ocis/issues/9168 and #843
The envvar used was the wrong one, most likely a c/p error - fixed.
Note, dev docs are correct - checked.
@rcrisanti fyi
=> Update prometheus.adoc - correct wrong envvar used

modules/ROOT/pages/monitoring/prometheus.adoc
=> [5.0] [PR 847] Update prometheus.adoc - correct wrong envvar used

modules/ROOT/pages/deployment/services/s-list/thumbnails.adoc
Fixes: #849 (Thumbnail service description update needed)
- Add a description about a new envvar
- Text fixes and improvements
- Add an internal comment that Thumbnail Processors are not covered here but referenced to dev docs.
NO backport.
=> Update Thumbnail service

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
Fixes: #850 (Missing details in the 'Restore Trash-Bins Items' doc section in storage-users)
References: https://github.com/owncloud/ocis/pull/9298 ([docs-only] fix two service readme's)
Update the text with regards to Restore Trash-Bins Items.
NO backport.
=> Update Restore Trash-Bins Items in storage-users

modules/ROOT/pages/maintenance/b-r/backup_considerations.adoc, modules/ROOT/partials/nav.adoc
Fixes: #851 (Update backup docs)
A new page about backup considerations. This gives an overview about folder structures, content and impacts.
=> Backup Considerations

modules/ROOT/pages/deployment/services/s-list/thumbnails.adoc
Referencing: https://github.com/owncloud/ocis/pull/9299 (Thumbnailer respect secure view)
Adding a short sentence about the thumbnail behavior when using SecureView.
No backport.
=> Thumbnails and SecureView

modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/partials/multi-location/idm-https-reverse-proxy.adoc
Part of #775 (Evaluate Easy Entry Docs)
This PR improves and fixes the `Minimal Bare Metal` deployment.
This is a necessary step in the overall deployment examples generation process.
Tested locally, works.
@tbsbdr as discussed.
=> Improve and fix the Minimal Bare Metal deployment

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Added documentation for the Helm chart for a new feature with custom CA chains.
https://github.com/owncloud/ocis-charts/pull/599
Needs Backport to 5.0
=> Added custom ca chain to helm doc

modules/ROOT/pages/deployment/services/s-list/idp.adoc
Based on a chat in matrix, add a note in the IDP service that it has no backchannel logout capability.
@rhafer fyi
=> Add backchannel logout inability in IDP

site.yml
This is just for local builds (corrected already in docs for the web some time ago),
the `ocis-actual-version` attribute gets updated to 5.0.5, needed when testing new content.
=> Correct the ocis-actual-version attribute for local builds

antora.yml
Missed to correct the latest stable patch release for 5.0 --> 5.0.5
Only for the 5.0 branch !
=> Correcting the latest ocis stable version rendered for 5.0

site.yml
=> [5.0] [PR 875] Correct the ocis-actual-version attribute for local builds

modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/sharing.adoc
After falling into the pit not carefully reading the banned pwd list docs, I improved visibility that it is restriced to `public link password validation`.
=> Make banned passwords usecase more visible

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Reverts owncloud/docs-ocis#871
This was merged too early as the corresponding charts PR is still not merged and has been changed a lot.
Note that it has been decided to remove the HC docs until those are a "product" but due to time constraints this had not happened so far.
@d7oc as discussed, it affects only master of the admin docs.
@b1schumacher fyi
=> Revert "Added custom ca chain to helm doc"

antora.yml, modules/ROOT/pages/index.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc, site.yml
Implement rolling and production releases in the ocis admin docs.
Note that any rolling version change only needs a change in the docs repo in site.yml
The rest is automated 😄 
Here is a screenshot how it looks:
=> Enable Rolling Releases in master (next)

modules/ROOT/pages/deployment/services/services.adoc
This was missing in the description, also for 5 and master.
But as we need to backport, this is step by step.
Backport to 5.0 and 4.0
=> Add that no services have been added in ocis v4

modules/ROOT/pages/deployment/services/services.adoc
This was missing in the description, for 5 and master.
But as we need to backport, this is step by step.
=> Add which services have been added in ocis v5

modules/ROOT/pages/deployment/services/services.adoc
This was missing in the description for master.
NO Backport
Needs to be merged AFTER #899
=> Add which services have been added in ocis master

modules/ROOT/pages/deployment/services/services.adoc
Missed to add the collaboration service.
No backport.
=> Missed collaboration service in added services in master

antora.yml, modules/ROOT/pages/conf-examples/office/ext-files/app-registry.adoc, modules/ROOT/pages/conf-examples/office/ext-files/docker-compose.adoc, modules/ROOT/pages/conf-examples/office/ext-files/env.adoc, modules/ROOT/pages/conf-examples/office/ext-files/wopiserver.adoc, modules/ROOT/pages/conf-examples/office/office-integration.adoc, modules/ROOT/pages/deployment/container/container-setup.adoc, modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc, modules/ROOT/pages/deployment/services/env-var-changes.adoc, modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc, modules/ROOT/pages/deployment/wopi/wopi.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/migration/upgrading-ocis.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc, modules/ROOT/partials/multi-location/compose-version.adoc, modules/ROOT/partials/multi-location/tab-text.adoc
References: #903 (Slim down and reduce complexity of the 'env-and-yaml' handling)
Attributes used needed a refactoring as there were some legacy things still present and attribute name to usage intention was not longer 1:1
With this PR, these changes help to read and understand some internal structures and usages much better. It is now also future proof.
=> Refactor attributes used

modules/ROOT/pages/maintenance/commands/backup-consistency.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/pages/maintenance/commands/revisions-cleanup.adoc, modules/ROOT/pages/maintenance/commands/trash.adoc
Fixes: #887 (Purge-Revision CLI)
* Make the maintenance page devided into `offline` and `online` command sections.
* Add storage path explanation
* Add 3 CLI commands
* Move the reset pwd command into the offline section
No backport!
=> Add offline CLI commands to maintenence

modules/ROOT/pages/deployment/services/s-list/search.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/pages/maintenance/space-ids/space-ids.adoc
Fixes: #878 (Allow reindexing all spaces)
Add a new argument to the reindex search command.
No backport.
=> Add --all-spaces to search command

modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/partials/deployment/services/env-and-yaml.adoc, modules/ROOT/partials/multi-location/idm-https-reverse-proxy.adoc
Two special envvars `OCIS_RUNTIME_PORT` and `OCIS_RUNTIME_HOST` were missing in the docs + description.
=> Fix missing special envvars

antora.yml
References: https://github.com/owncloud/docs/pull/4978 (Prepare for ocis 5.0.6)
This PR is for 5.0 only and prepares for the upcoming ocis 5.0.6 patch release.
Only merge when the release has been published!
=> Prepare for ocis 5.0.6

modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/s-list/notifications.adoc
Fixes: #883 (Update the Notifications service doc)
Add a note that the notifications service will not start automatically anymore and must be started manually.
No backport.
=> No autostart for notification service

modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Add a small comment what the abbreviation of the column `IV` means.
No backport, master only.
=> Explain the IV column in envvar tables

modules/ROOT/pages/deployment/services/ports-used.adoc, modules/ROOT/pages/deployment/services/s-list/auth-app.adoc, modules/ROOT/pages/deployment/services/services.adoc, modules/ROOT/partials/deployment/services/auth-service-family.adoc, modules/ROOT/partials/nav.adoc
Fixes: #913 (New service: auth-app)
The `Auth-App` service is added with this PR.
**Note**: Merge when the auth-app service has been merged in ocis.
No Backport.
=> Add Auth-App service

modules/ROOT/partials/deployment/services/env-and-yaml.adoc
Fixes: 934 ([QA] Misleading wording 'has been chosen on purpose')
Text fix.
=> Fix yaml file name explanation text

modules/ROOT/pages/deployment/general/ocis-init.adoc
This is a preparation for the next PR which will implement `--diff`.
=> Update ocis.init (prepare for --diff)

modules/ROOT/pages/deployment/general/ocis-init.adoc, modules/ROOT/pages/migration/upgrading-ocis.adoc
Fixes: #935 (Add a --diff mode to ocis init)
The --diff argument has been added in ocis master.
* Add a description in `ocis init`
* Add a note in the upgrade guide
NO backport !
=> Add the ocis init --diff command argument

modules/ROOT/pages/deployment/services/s-list/proxy.adoc
Fixes: #888 (Autoprovisioning envvars documentation)
Add a proxy service documentation about `Automatic User and Group Provisioning`
No backport.
=> Autoprovisioning documentation

modules/ROOT/pages/deployment/services/s-list/ocm.adoc
Fixes: #951 (Document the expected location of the ocmproviders.json file)
Text fix related to changes in the ocis repo.
No backport, master only
=> ocm service text update

modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc, modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc, modules/ROOT/partials/multi-location/compose-version-production.adoc, modules/ROOT/partials/multi-location/compose-version-rolling.adoc
This PR adapts the Ubuntu deployment examples to rolling releases.
The changes have been tested by deploying on a local server using self signed certificates and on Hetzner with full certificates.
Note that some fixes have been added to the `ocis_full` deployment example in the ocis repo. Therefore this PR is only valid when the new rolling release (6.3.0) will be published next week. I put it on draft to avoid accidential merging.
* Adapt text blocks
* Moving the Update section into the partial.
* Create dynamic settings and text elements that adapt the content automatically when we do a new stable release (new branch). This is necessary because rolling != production
Some text blocks will be selectively backported to 5.0 for a harmonized look and feel.
I will do more tests, but this PR …
=> Adapt Ubuntu deployment examples to rolling

modules/ROOT/pages/deployment/services/s-list/web.adoc, modules/ROOT/pages/deployment/webui/webui-customisation.adoc, modules/ROOT/pages/deployment/webui/webui.adoc, modules/ROOT/partials/nav.adoc
The current Web UI documentation urgently needed some care, especially with rolling 6 which provides many apps.
* Remove the not necessary Web UI intro page, three line content is much to less
Keep an alias so nothing breaks
* Collect and order all remaining Configuration and Theming content from web into their respective individual pages
* From web, link the content pages
Compared to the ocis repo/ocis dev, web reads here much easier as it is not overloaded, this is by design.
Textwise, except adding a link to the extensions repo, nothing got changed but moved only.
No backport
=> Streamline the Web UI documentation

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
This PR updates the bare metal deployments:
* Show the correct version depending on the branch, same as we do in Ubuntu examples
* Add an Update section in the systemd version, same as we do in Ubuntu examples
No backport, master only
=> Update the bare metal deployments

modules/ROOT/pages/deployment/services/s-list/graph.adoc
Referencing: https://github.com/owncloud/ocis/pull/9902 (Add TRANSLATION_PATH envvar to graph service)
Add the description for the translation and default language.
Only merge after the referenced PR got merged.
No Backport
=> Add Graph service translation and default language

modules/ROOT/pages/maintenance/commands/revisions-cleanup.adoc
References: https://github.com/owncloud/ocis/pull/9904 ([docs-only] Forgotten revisions purge docs)
Add command parameter to revision purge.
Only merge after the referenced PR gor merged.
No Backport
=> Add glob/worker to revision purge CLI

modules/ROOT/pages/deployment/services/s-list/gateway.adoc
Fixes: #683 ([5.0] The gateway service has changed caching settings)
Small text fix, the caching changes have already been implemented for both branches.
=> Small gateway service description fix

modules/ROOT/pages/deployment/services/s-list/settings.adoc
Fixes: #852 (Add custom roles (settings service))
Add the custom roles description sourced from the ocis repo.
The full example is not added but linked to the dev docs.
No backport.
=> Add custom roles in the settings service

modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
References: #974 (Fix updating in docker compose examples)
This is the text backport variant of the referenced PR above.
=> [5.0] Fix update in depl examples

site.yml
Referencing: https://github.com/owncloud/docs/pull/4985 (Make ocis 5.0.7 as default production)
Only for local building the docs here.
Only merge after release notes have been merged - setting to draft therefore.
=> Local only, ocis 5.0.7

modules/ROOT/pages/deployment/services/s-list/notifications.adoc
The placeholder text in notfications need an update to ease readability.
There is no content change but reordering only.
Will fix that in the ocis repo too.
=> Reordering some text in notifications to improve readability

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc
Fixes: #952 ([5.0] Backport Sessions Command)
References: https://github.com/owncloud/ocis/issues/9962 (Patch Release 5.0.7)
The sessions command has been backported in ocis to 5.0
This PR does a selective text backport of content already existing in master to the admin docs 5.0
Because this needs release 5.0.7 which will contain the code change, I set this to draft to avoid accidentially merging.
=> [5.0] only selective backport of session commands

modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc, modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Same as we (will) have in the rolling deployment example #948, the docker volumes got configurable for 5.0, see: https://github.com/owncloud/ocis/pull/9847 ([docs-only][stable-5.0] ocis_wopi deployment example, make data and config volumes configurable). This PR updates the deployment example to reflect the new capability. In addition, the upgrade section is moved into the shared content as it is the same for both setups. Note that the texts are just copied from #948.
Because this PR mandatory needs ocis 5.0.7 to be released, hopefully soon, I put it on draft to avoid accidentially merging.
=> [5.0] Selective backport: confingurable volumes in deployment example

antora.yml
Need to set the actual ocis production version to 5.0.7 in the 5.0 branch needed for the build process.
=> Set 5.0.7 as default in the 5.0 branch

modules/ROOT/pages/maintenance/commands/rolling-back-and-forward.adoc
the `-l` option does not exist (at least not on 6.1.0)
I believe it should be `list`
also other details of the output fixed
=> fix migration command

modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
References: #996 ([5.0] [PR 992] Update compose deployments based on feedback)
Introduced with the referenced PR, an attribute got overwritten that is different in master, fixed now.
Found by running a full local docs build:
```
[10:29:10.394] WARN (asciidoctor): skipping reference to missing attribute: version-type
file: modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
source: https://github.com/owncloud/docs-ocis.git (branch: 5.0)
```
=> [5.0] Fix using the correct attribute

modules/ROOT/pages/deployment/services/s-list/auth-app.adoc
Missed a title text to the envvars list block in auth-app startup - fixed.
No backport
=> Add a title text to the envvars list block in auth-app startup

modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc, site.yml
Fixes: #994 (Update graph service)
* Updates the Graph service description
(the text is sourced from the referenced issue/PR)
* Fixes a typo in a shared document
* Updates site.yml ocis rolling version, relevant for local build only
No backport
=> Update the Graph Service description

modules/ROOT/pages/deployment/services/caching.adoc, modules/ROOT/pages/deployment/services/env-vars-special-scope.adoc, modules/ROOT/pages/deployment/services/registry.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/nats.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/thumbnails.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/multi-location/caching-list.adoc, modules/ROOT/partials/nav.adoc
Fixes: #972 (Registry and cache/store update)
* Add a new Registry page
* Adapt content for the caching page
* Remove deprecated caches/stores/registries
* Adapt the caching partial to be included in the caching page
* Add missing event store for services where we have caching
* Harmonize the sort order and location of cache/store and event bus over all related servcies
No backport
=> Registry and cache store updates

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc, modules/ROOT/pages/migration/upgrading-ocis.adoc, modules/ROOT/pages/migration/upgrading_2.0.0_3.0.0.adoc, modules/ROOT/pages/migration/upgrading_3.0.0_4.0.0.adoc, modules/ROOT/pages/migration/upgrading_4.0.0_5.0.0.adoc, modules/ROOT/pages/quickguide/quickguide.adoc, site.yml
References: #1010 (Make the dynamics of stable/production more robust)
This are the changes relevant for 5.0 driven by the referenced PR. It is a partial mini backport.
=> Fix ocis-downloadpage-url attribute usage

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc, modules/ROOT/pages/deployment/services/s-list/thumbnails.adoc
Fixes: #1009 (Thumbnail generator changes)
* Adding an admin relevant text to the thumbnail service because container deployments use an external shared libraries.
* Also add a text to the bare metal deployment examples referencing to thumbnail service.
* Some small text improvements in the bare metal deployments and the thumbnail service.
No backport.
=> New thumbnail generator for container deployments

modules/ROOT/pages/deployment/services/s-list/collaboration.adoc
Fixes: #1013 (Documentation for collaboration refers to COLLABORATION_APP_WOPISRC instead of COLLABORATION_WOPI_SRC)
The envvar name was wrong, needs fixing in the dev docs too.
=> Fix envvar name in collaboration service

site.yml
Set the attribute to use ocis 6.6.0 - local build relevant only.
Only merge when the release has been published!!
=> Prepare for ocis 6.6.0 (local build relevant only)

modules/ROOT/pages/deployment/services/ports-used.adoc
References: https://github.com/owncloud/ocis/pull/10394 (add new range for ocdav)
* New port ranges for ocdav
* Removed `store` ports (missed do to that once)
No backport
=> Fix ports-used

modules/ROOT/pages/deployment/services/s-list/collaboration.adoc, modules/ROOT/partials/multi-location/caching-list.adoc
Fixes: #1021 (Collaboration service update)
* Add **store** block
* Problem and reason for using `COLLABORATION_WOPI_SHORTTOKENS`
* Add a new conditional rendering for services not using the event bus, but we reference to it
* Small text fixes in the partial
No backport
Only merge if the ocis PR got merged, see referenced issue.
=> Update collaboration using a store + partial text fixes

modules/ROOT/pages/deployment/services/s-list/sse.adoc
Fixes: #1023 (Add SSE keep alive info)
Add explaining text for the SSE keep alive envvar.
Text 1:1 from the referenced ocis PR.
Only merge when the referenced ocis PR got merged.
=> Add SSE keep alive

modules/ROOT/pages/deployment/services/caching.adoc, modules/ROOT/pages/deployment/services/s-list/activitylog.adoc, modules/ROOT/pages/deployment/services/s-list/collaboration.adoc, modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/multi-location/cache-store.adoc
This PR implemants:
* A better naming for the store attribute `is_stat` --> `is_store`.
* Renames the partial to reflect it is about cache and store
No backport
(if we went to go for this, we need to do a partial backport, because 7 has more services than 5)
Locally tested, no build errors, renders as before.
=> Proper naming of store attribute/partial

site.yml
References: https://github.com/owncloud/docs/pull/4994 (Add ocis rolling 6.6.1)
Only relevant for local building
=> ocis 6.6.1 rolling (local build relevant only)

modules/ROOT/pages/deployment/services/s-list/activitylog.adoc, modules/ROOT/pages/deployment/services/s-list/collaboration.adoc, modules/ROOT/pages/deployment/services/s-list/eventhistory.adoc, modules/ROOT/pages/deployment/services/s-list/frontend.adoc, modules/ROOT/pages/deployment/services/s-list/gateway.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/notifications.adoc, modules/ROOT/pages/deployment/services/s-list/postprocessing.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/deployment/services/s-list/storage-system.adoc, modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/deployment/services/s-list/userlog.adoc, modules/ROOT/partials/multi-location/cache-store.adoc
This PR changes two things:
* Use [tag filtering](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/#tag-filtering) instead using commented tags
* Add a comment above the include for translations making it easier to identify
No text changes
No backport
=> Use tag filtering and add comment in various pages

modules/ROOT/pages/depl-examples/container-setup.adoc, modules/ROOT/partials/nav.adoc
The container setup page (docker run):
* is now located in the deployment examples, a page alias has been set.
* got some text fixes.
=> Relocate and update the container setup page 

modules/ROOT/pages/maintenance/commands/commands.adoc
=> Single character typo fix in maintenance commands page

modules/ROOT/pages/maintenance/commands/commands.adoc
The paths had missing or wrong components - fixed.
Referencing the base data path description.
=> Fix path for cli --basePath parameter

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
This PR updates the common compose deployment text with an Update and Upgrade section, necessary for the upcoming v7.
Depending on the release type, different texts are printed.
No backport !!
=> Update the compose examples to be ready to upgrade for the next release

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Added an extra step to add accessible oCIS domain in `externalDomain`.
The value of the `externalDomain` was removed in PR https://github.com/owncloud/ocis-charts/pull/562.
If the `externalDomain` is not provided we get the following error:
```console
Error: INSTALLATION FAILED: execution error at (ocis/templates/webfinger/deployment.yaml:61:33): externalDomain needs to be set
```
=> [docs] add step to configure externalDomain

modules/ROOT/examples/deployment/container/orchestration/s3ng-s3-access-key-id-secret-tab-1.yaml, modules/ROOT/examples/deployment/container/orchestration/s3ng-s3-access-key-id-secret-tab-2.yaml, modules/ROOT/examples/deployment/container/orchestration/s3ng-s3-access-key-id-secret-tab-3.yaml
This PR updates the secret name for s3ng storage configuration. The secret name was set same as Email Notification config. So, updated the secret name to `s3-credentials-secret`.
=> [docs] fix secrets name for s3 credential

modules/ROOT/pages/maintenance/space-ids/space-ids.adoc, modules/ROOT/partials/multi-location/get-bearer-token.adoc
The document how to get a space ID was faulty and outdated. This PR fixes this.
=> Fix how to get the space ID documentation

modules/ROOT/pages/depl-examples/bare-metal.adoc, modules/ROOT/pages/depl-examples/minimal-bare-metal.adoc
Fixes: #1052 ([QA] Upgrade procedure fails to shut down ocis when using systemd)
References: https://github.com/owncloud/docs-ocis/pull/1029#pullrequestreview-2436660166
This PR fixes:
* `killall` instead of `kill` for shutting down minimal bare metal
(not bare metal, this uses systemd)
* Improves the binary installation routine by using links
=> Update bare metal deployments

antora.yml, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc
The attribute `download-type` is computed dynamically in master and higher, but are static in 5.0.
The attribute `ocis_wopi` is moved to `antora.yml`. In master and higher it is also in antora.yml but with a different value.
=> [5.0] Fix attributes which are treated different in this branch

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Change the compose guides to make the SMTP_SENDER a mandatory setting.
As discussed with @kobergj 
=> Make SMTP_SENDER a mandatory setting

modules/ROOT/pages/deployment/services/s-list/antivirus.adoc, modules/ROOT/pages/deployment/services/s-list/audit.adoc, modules/ROOT/pages/deployment/services/s-list/auth-app.adoc, modules/ROOT/pages/deployment/services/s-list/collaboration.adoc, modules/ROOT/pages/deployment/services/s-list/invitations.adoc, modules/ROOT/pages/deployment/services/s-list/notifications.adoc, modules/ROOT/pages/deployment/services/s-list/policies.adoc
This PR adds a note to all services that are excluded from autostart and must be started manually.
Here is the [code reference](https://github.com/owncloud/ocis/blob/master/ocis/pkg/runtime/service/service.go#L313-L347) in the ocis repo.
No backport, because half of the services did not exist in 5.0
=> Add a note for all services that must be started manually

modules/ROOT/pages/deployment/storage/s3.adoc
The AWS S3 bucket is automatically encrypted.
=> Add that the S3 blob is encrypted automatically on the AWS side

modules/ROOT/pages/monitoring/prometheus.adoc
Backport of #1073
The activitylog has been removed because it is not present in 5.0
=> [5.0] [PR 1073] Add metrics info for stand alone services

modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-hetzner.adoc, modules/ROOT/pages/depl-examples/ubuntu-compose/ubuntu-compose-prod.adoc, modules/ROOT/pages/deployment/services/s-list/antivirus.adoc
Fixes: #1042 (Antivirus and memory consumption)
References: https://github.com/owncloud/ocis/pull/10681 ([docs-only] Add memory considerations to the antivirus service)
This info is necessary for any deployment and in particular referenced in the compose deployment examples.
=> The antivirtus service has additional memory requirements

modules/ROOT/pages/maintenance/commands/revisions-cleanup.adoc
Make the --dry-run=false option more prominent with the ocis revisions purge command.
compare https://central.owncloud.org/t/4tb-hd-almost-full-with-only-1-5tb-storage-used-and-broken-trashbin/50168/3
=> Add note about dry-run

modules/ROOT/pages/deployment/services/s-list/auth-app.adoc
References: https://github.com/owncloud/ocis/pull/10620 ([docs-only] Describe CLI-API commands in auth-app to manage tokens)
The auth-app can manage tokens via the API. Content is taken from the dev docs + adaptions for admin docs.
=> Update auth-app: API access

modules/ROOT/pages/deployment/services/s-list/auth-app.adoc
The impersonate API for the `auth-app` was missing.
No backport
=> Add impersonate api for auth-api

modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
Fixes: #716 (Document how to configure K3S to resolve custom domains to the host)
Just a small docs addon to orchestration.
No backport
=> Add K3S info to orchestration

modules/ROOT/pages/deployment/storage/s3.adoc
Mistyped the envvar which is not existing.
@individual-it thanks for catching 👍
=> Fix wrong envvar in S3 (SYSTEM --> USERS)

.drone.star
These are the changes necessary to finalize the creation of the 7.0 branch.
* The 7.0 branch is already pushed and prepared and is included in the branch protection rules.
@phil-davis
Post merging this, we need to backport all relevant changes to 7.0
=> Changes necessary for ocis 7.0

.drone.star, antora.yml, site.yml
These are the changes necessary to finalize the creation of the 7.1 branch.
* The 7.1 branch is already pushed and prepared and is included in the branch protection rules.
* When 7.1 is finally out, the 5.0 branch can be archived, see step 3 in [Create a New Version Branch](https://github.com/owncloud/docs-ocis/blob/master/docs/new-version-branch.md)
* Note, that the 7.1 branch in this repo is already created, but the `latest` pointer on the web will be set to it automatically when the tag in oics is set. This means, that in the docs homepage, `latest` will point to 7.0 until the tag in ocis is set accordingly. When merging the corresponding doc PR, 5.0 will be dropped from the web.
* Note that this PR must be merged **before** the 7.1 tag in ocis is set to avoid a 404 for `latest`.
* …
=> Changes necessary for 7.1

modules/ROOT/pages/deployment/services/env-var-changes.adoc
As a first fix, the PR updates the delta range for changed envvars.
=> Fix the delta range for envvars

modules/ROOT/pages/deployment/services/s-list/notifications.adoc, modules/ROOT/pages/deployment/services/s-list/settings.adoc, modules/ROOT/pages/maintenance/commands/changed-cli.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc, modules/ROOT/pages/migration/upgrading-ocis.adoc, modules/ROOT/pages/migration/upgrading_7.0.0_7.1.0.adoc
Fixes: #1111 (Notification Service gets a store and a CLI command)
Fixes: #1104 (Settings Service gets Translations)
References: https://github.com/owncloud/docs/pull/5007 (Enable ocis 7.1)
* Add new CLI in maintenance section
* Add notification service changes
* Add settings service changes
* Update Migration and Upgrade guide
(Note that the release notes will point to them)
A local build runs fine.
=> Changes for 7.1

antora.yml, modules/ROOT/pages/additional-information/knowledge-base.adoc, modules/ROOT/pages/deployment/general/general-info.adoc, modules/ROOT/pages/deployment/services/s-list/graph.adoc, modules/ROOT/pages/deployment/services/s-list/idp.adoc, modules/ROOT/pages/deployment/services/s-list/proxy.adoc, modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc, modules/ROOT/partials/multi-location/compose-version.adoc
References: #1140 (For 7.1, use the real 7.1 related branches in antora.yml)
This PR simplifies respectively removes unused attributes including paths when these attributes are used.
Needs a _careful_ backport to 7.1 ONLY
=> Simplify attribute usage and paths

antora.yml
This PR updates ocis to 7.1.1
Only for the 7.1 branch.
Note that there will be 2 additional PR's in docs (global attributes) and docs-main (release notes).
=> Update ocis to 7.1.1

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc, modules/ROOT/pages/maintenance/commands/commands.adoc
Fixes: #1155 (CLI: remove stale uploads)
Add a new storage users cli command: `ocis storage-users uploads delete-stale-nodes`.
No backport.
=> Add Storage-Users CLI: Remove Stale Uploads

modules/ROOT/pages/deployment/services/s-list/proxy.adoc
Fixes: #1158 (Add Space management trough OIDC Claims)
This adds documentation how to manage Spaces through OIDC claims.
I also did some section restructuring of the sections to better fit in the new content.
The rendered version is currently visible on staging.
No backport.
=> Add Space management trough OIDC Claims

modules/ROOT/partials/depl-examples/ubuntu-compose/shared-setup.adoc
Fixes: #1169 (office deployment hardening (ocis_full))
* Remove WOPI
* Fix the use of text color for inline code
Note that `ocis-full` currently points to 6.1 which still has WOPI, but with Addams (7.2) this is fixed automatically.
Rendered locally, works fine.
NO backport, will be part of 7.2
=> Update the deployment examples, the WOPI domain is not exposed anymore

modules/ROOT/pages/migration/upgrading_7.0.0_7.1.0.adoc
Refernces: #1176 (Add changed envvar link to migration document)(master)
This is a kind of backport of the change made in master but to the correct document which is different in 7.1
=> [7.1] [PR 1176] Add changed envvar link

modules/ROOT/pages/deployment/services/s-list/storage-users.adoc
Fixes: #1180 (Update Storage-Users docs)
`--processing=false` --> `--processing=true`
Backport to 7.2 and 7.1
=> Fix storage-users command for resume non virus infected

modules/ROOT/pages/deployment/storage/s3.adoc
This PR corrects a typo in the environment variable for S3 storage configuration.
The variable STORAGE_USERS_DRIVER is updated to STORAGE_SYSTEM_DRIVER to match the actual variable that should be used here.
=> Change STORAGE_USERS_DRIVER to STORAGE_SYSTEM_DRIVER
